# Generated by Django 5.1.15 on 2026-03-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_code', models.CharField(db_column='code', max_length=20, unique=True)),
                ('date', models.DateField()),
                ('weight_gross', models.DecimalField(blank=True, db_column='weight_gross_kg', decimal_places=2, max_digits=10, null=True)),
                ('weight_net', models.DecimalField(blank=True, db_column='weight_net_kg', decimal_places=2, max_digits=10, null=True)),
                ('packaging_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pallet_count', models.IntegerField(blank=True, null=True)),
                ('pallet_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('box_count', models.IntegerField(blank=True, null=True)),
                ('rejected_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('truck_head_id', models.BigIntegerField(blank=True, null=True)),
                ('trailer_id', models.BigIntegerField(blank=True, null=True)),
                ('driver_id', models.BigIntegerField(blank=True, null=True)),
                ('trip_id', models.BigIntegerField(blank=True, null=True)),
                ('vehicle_responsible', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('transit_days', models.IntegerField(blank=True, null=True)),
                ('shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('has_peregruz', models.BooleanField(default=False)),
                ('peregruz_city', models.CharField(blank=True, max_length=100, null=True)),
                ('peregruz_date', models.DateTimeField(blank=True, null=True)),
                ('is_gapy_satys', models.BooleanField(default=False)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loading_started_at', models.DateTimeField(blank=True, null=True)),
                ('customs_entry_at', models.DateTimeField(blank=True, null=True)),
                ('customs_exit_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('border_crossed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('sale_started_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ended_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_condition', models.CharField(blank=True, choices=[('OK', 'OK'), ('ISSUE', 'Issue'), ('BREAKDOWN', 'Breakdown'), ('RETURNED', 'Returned')], max_length=20, null=True)),
                ('vehicle_condition_note', models.CharField(blank=True, max_length=300, null=True)),
                ('route_note', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_status_note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('border_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.borderpoint')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.customer')),
                ('import_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.importfirm')),
                ('loading_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loadinglocation')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.season')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.shipmentstatustype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipments', to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tomatovariety')),
            ],
            options={
                'db_table': 'export_shipments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('mentions', models.CharField(blank=True, max_length=500, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='export.shipmentcomment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='export.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_shipment_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='export.shipment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shipmentstatustype')),
            ],
            options={
                'db_table': 'export_shipment_status_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentBlockSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.greenhouseblock')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_sources', to='export.shipment')),
            ],
            options={
                'db_table': 'export_shipment_block_sources',
                'unique_together': {('shipment', 'block')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentFirmSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('split_order', models.IntegerField(default=1)),
                ('export_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exportfirm')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_splits', to='export.shipment')),
            ],
            options={
                'db_table': 'export_shipment_firm_splits',
                'ordering': ['split_order'],
                'unique_together': {('shipment', 'export_firm')},
            },
        ),
    ]
