# Generated by Django 5.1.15 on 2026-03-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('export', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='core.city')),
                ('entered_by', models.ForeignKey(blank=True, db_column='entered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_entries_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_price_entries',
                'ordering': ['-date', 'city'],
                'constraints': [models.UniqueConstraint(fields=('date', 'city'), name='uq_price_date_city')],
            },
        ),
        migrations.CreateModel(
            name='QuotaAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warning_80_sent', models.BooleanField(default=False)),
                ('warning_90_sent', models.BooleanField(default=False)),
                ('warning_95_sent', models.BooleanField(default=False)),
                ('export_firm', models.ForeignKey(db_column='export_firm_id', on_delete=django.db.models.deletion.PROTECT, related_name='quota_allocations', to='core.exportfirm')),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season')),
            ],
            options={
                'db_table': 'export_quota_allocations',
                'ordering': ['export_firm__name_en'],
                'constraints': [models.UniqueConstraint(fields=('season', 'export_firm'), name='uq_quota_season_firm')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyHarvestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('monday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuesday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wednesday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thursday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('friday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saturday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuesday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wednesday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thursday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('friday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saturday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, to='core.greenhouseblock')),
                ('entered_by', models.ForeignKey(blank=True, db_column='entered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_entered', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season')),
            ],
            options={
                'db_table': 'export_weekly_harvest_plans',
                'ordering': ['year', 'week_number', 'block'],
                'constraints': [models.UniqueConstraint(fields=('season', 'block', 'week_number', 'year'), name='uq_weekly_plan')],
            },
        ),
    ]
