# Generated by Django 5.1.15 on 2026-03-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_priceentry_quotaallocation_weeklyharvestplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azyk_maglumatnama', models.BooleanField(default=False)),
                ('suriji_gozukdiriji', models.BooleanField(default=False)),
                ('tls', models.BooleanField(default=False)),
                ('lab_sertifikat', models.BooleanField(default=False)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='export.shipment')),
            ],
            options={
                'db_table': 'export_quality_documents',
            },
        ),
    ]
