# Generated by Django 5.1.15 on 2026-04-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck_destination'),
        ('export', '0002_weeklyharvestplan_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDestinationSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '[export].[truck_destination_splits]',
                'ordering': ['destination__sort_order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='weeklytruckallocation',
            name='chk_trk_russia_gte0',
        ),
        migrations.RemoveConstraint(
            model_name='weeklytruckallocation',
            name='chk_trk_kz_gte0',
        ),
        migrations.RemoveConstraint(
            model_name='weeklytruckallocation',
            name='chk_trk_gapy_gte0',
        ),
        migrations.RemoveField(
            model_name='weeklytruckallocation',
            name='gapy_satys_trucks',
        ),
        migrations.RemoveField(
            model_name='weeklytruckallocation',
            name='kazakhstan_trucks',
        ),
        migrations.RemoveField(
            model_name='weeklytruckallocation',
            name='russia_trucks',
        ),
        migrations.AddField(
            model_name='truckdestinationsplit',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_splits', to='core.truckdestination'),
        ),
        migrations.AddField(
            model_name='truckdestinationsplit',
            name='truck_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_splits', to='export.weeklytruckallocation'),
        ),
        migrations.AddConstraint(
            model_name='truckdestinationsplit',
            constraint=models.UniqueConstraint(fields=('truck_allocation', 'destination'), name='uq_truck_dest_split'),
        ),
        migrations.AddConstraint(
            model_name='truckdestinationsplit',
            constraint=models.CheckConstraint(condition=models.Q(('truck_count__gte', 0)), name='chk_truck_dest_count_gte0'),
        ),
    ]
