# Generated by Django 5.1.15 on 2026-03-27 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_qualitydocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market_name', models.CharField(max_length=100)),
                ('price_type', models.CharField(blank=True, max_length=30, null=True)),
                ('variety_type', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, db_column='entered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_prices_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_domestic_market_prices',
                'ordering': ['-date', 'market_name'],
                'indexes': [models.Index(fields=['date', 'market_name', 'price_type', 'variety_type'], name='ix_domestic_price')],
            },
        ),
    ]
