# Generated by Django 5.1.15 on 2026-05-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_sheet_row_setting_hidden_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
