# Generated by Django 5.1.15 on 2026-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_truck_destination_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='actual_weekly_total_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly actual total when per-day breakdown is unavailable', max_digits=10, null=True),
        ),
    ]
