# Generated by Django 5.1.15 on 2026-03-27 12:34
# Manually corrected: Django autodetector paired renames incorrectly.
# Correct mapping per DDL v5.1: tls → hil_sertifikaty, lab_sertifikat → kalibrowka_analiz

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_domesticmarketprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitydocument',
            old_name='tls',
            new_name='hil_sertifikaty',
        ),
        migrations.RenameField(
            model_name='qualitydocument',
            old_name='lab_sertifikat',
            new_name='kalibrowka_analiz',
        ),
    ]
