# Generated by Django 5.1.15 on 2026-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_notification_stuck_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrowsetting',
            name='who_en',
            field=models.CharField(blank=True, help_text='"Who" column override in English.', max_length=80),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='who_ru',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='"Who" column override in Russian.', max_length=80),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='who_tk',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='"Who" column override in Turkmen. Falls back to default_who_key i18n.', max_length=80),
        ),
    ]
