# Generated by Django 5.1.15 on 2026-03-27 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_rename_lab_sertifikat_qualitydocument_hil_sertifikaty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_usd', models.DecimalField(blank=True, db_column='total_revenue_usd', decimal_places=2, max_digits=12, null=True)),
                ('weight_sold_kg', models.DecimalField(blank=True, db_column='sold_weight_kg', decimal_places=2, max_digits=10, null=True)),
                ('weight_rejected_kg', models.DecimalField(blank=True, db_column='waste_kg', decimal_places=2, max_digits=10, null=True)),
                ('transport_cost_usd', models.DecimalField(blank=True, db_column='transport_expenses', decimal_places=2, max_digits=10, null=True)),
                ('market_fee_usd', models.DecimalField(blank=True, db_column='storage_expenses', decimal_places=2, max_digits=10, null=True)),
                ('other_expenses_usd', models.DecimalField(blank=True, db_column='other_expenses', decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_reports_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_report', to='export.shipment')),
            ],
            options={
                'db_table': 'export_sales_reports',
            },
        ),
    ]
