# Generated by Django 5.1.15 on 2026-05-04 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_sheet_row_setting_who_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrowsetting',
            name='is_custom',
            field=models.BooleanField(db_index=True, default=False, help_text='True for admin-created runtime rows (Phase 5c). Values stored in ShipmentCustomFieldValue, not on Shipment.'),
        ),
        migrations.CreateModel(
            name='ShipmentCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='Free-text cell value. Empty string = explicitly cleared by user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(limit_choices_to={'is_custom': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_values', to='export.sheetrowsetting')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='export.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_shipment_custom_field_value',
                'constraints': [models.UniqueConstraint(fields=('shipment', 'row'), name='uq_shipment_custom_field')],
            },
        ),
    ]
