# Generated by Django 5.1.15 on 2026-04-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck_destination'),
        ('export', '0006_quota_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLocalSellPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('monday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuesday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wednesday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thursday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('friday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saturday_plan_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuesday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wednesday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thursday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('friday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saturday_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_sell_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, db_column='entered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_sell_plans_entered', to=settings.AUTH_USER_MODEL)),
                ('export_firm', models.ForeignKey(db_column='export_firm_id', on_delete=django.db.models.deletion.PROTECT, related_name='local_sell_plans', to='core.exportfirm')),
                ('rejected_by', models.ForeignKey(blank=True, db_column='rejected_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_sell_plans_rejected', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, db_column='season_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.season')),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_sell_plans_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '[export].[weekly_local_sell_plans]',
                'ordering': ['year', 'week_number', 'export_firm__name_en'],
                'indexes': [models.Index(fields=['status'], name='ix_local_sell_plan_status')],
                'constraints': [models.UniqueConstraint(fields=('export_firm', 'week_number', 'year'), name='uq_local_sell_plan'), models.CheckConstraint(condition=models.Q(('monday_plan_kg__gte', 0), ('tuesday_plan_kg__gte', 0), ('wednesday_plan_kg__gte', 0), ('thursday_plan_kg__gte', 0), ('friday_plan_kg__gte', 0), ('saturday_plan_kg__gte', 0)), name='chk_local_sell_plan_kg_gte0')],
            },
        ),
    ]
