# Generated by Django 5.1.15 on 2026-03-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_salesreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinansistAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('advance_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_finansist_advances',
                'ordering': ['-advance_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinansistAdvanceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_links', to='export.finansistadvance')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_links', to='export.shipment')),
            ],
            options={
                'db_table': 'export_finansist_advance_shipments',
                'unique_together': {('advance', 'shipment')},
            },
        ),
    ]
