# Generated by Django 5.1.15 on 2026-03-30 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domesticbuyer'),
        ('export', '0007_finansistadvance_finansistadvanceshipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variety', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tabel_no', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, related_name='domestic_sales', to='core.greenhouseblock')),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.PROTECT, related_name='domestic_sales', to='core.domesticbuyer')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_sales_created', to=settings.AUTH_USER_MODEL)),
                ('export_firm', models.ForeignKey(blank=True, db_column='export_firm_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exportfirm')),
            ],
            options={
                'db_table': 'export_domestic_sales',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTruckAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('total_planned_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_trucks_calc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('russia_trucks', models.IntegerField(default=0)),
                ('kazakhstan_trucks', models.IntegerField(default=0)),
                ('gapy_satys_trucks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, db_column='decided_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_allocations_decided', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season')),
            ],
            options={
                'db_table': 'export_weekly_truck_allocations',
                'ordering': ['year', 'week_number', 'day_of_week'],
                'unique_together': {('season', 'week_number', 'year', 'day_of_week')},
            },
        ),
    ]
