# Generated by Django 5.1.15 on 2026-04-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0007_weekly_local_sell_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='friday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='monday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='saturday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='thursday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='tuesday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklylocalsellplan',
            name='wednesday_actual_kg',
        ),
    ]
