# Generated by Django 5.1.15 on 2026-03-30 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domesticbuyer'),
        ('export', '0008_domesticsale_weeklytruckallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytruckallocation',
            name='total_trucks_calc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='quotaallocation',
            constraint=models.CheckConstraint(condition=models.Q(('used_kg__gte', 0)), name='chk_quota_used_kg_gte0'),
        ),
        migrations.AddConstraint(
            model_name='quotaallocation',
            constraint=models.CheckConstraint(condition=models.Q(('granted_kg__gt', 0)), name='chk_quota_granted_kg_gt0'),
        ),
        migrations.AddConstraint(
            model_name='weeklyharvestplan',
            constraint=models.CheckConstraint(condition=models.Q(('monday_plan_kg__gte', 0), ('tuesday_plan_kg__gte', 0), ('wednesday_plan_kg__gte', 0), ('thursday_plan_kg__gte', 0), ('friday_plan_kg__gte', 0), ('saturday_plan_kg__gte', 0)), name='chk_harvest_plan_kg_gte0'),
        ),
        migrations.AddConstraint(
            model_name='weeklytruckallocation',
            constraint=models.CheckConstraint(condition=models.Q(('russia_trucks__gte', 0)), name='chk_trk_russia_gte0'),
        ),
        migrations.AddConstraint(
            model_name='weeklytruckallocation',
            constraint=models.CheckConstraint(condition=models.Q(('kazakhstan_trucks__gte', 0)), name='chk_trk_kz_gte0'),
        ),
        migrations.AddConstraint(
            model_name='weeklytruckallocation',
            constraint=models.CheckConstraint(condition=models.Q(('gapy_satys_trucks__gte', 0)), name='chk_trk_gapy_gte0'),
        ),
    ]
