# Generated by Django 5.1.15 on 2026-04-09 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck_destination'),
        ('export', '0008_weekly_local_sell_plan_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('product_type', models.CharField(choices=[('tomato', 'Tomato'), ('pepper', 'Pepper')], default='tomato', max_length=20)),
                ('matched_week', models.PositiveSmallIntegerField(help_text='ISO week number this issuance is matched to')),
                ('matched_year', models.PositiveSmallIntegerField(help_text='ISO year for matched_week')),
                ('is_manually_reassigned', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_issuances_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '[export].[quota_issuances]',
                'ordering': ['issue_date'],
            },
        ),
        migrations.CreateModel(
            name='QuotaIssuanceFirmAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_quota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('export_firm', models.ForeignKey(db_column='export_firm_id', on_delete=django.db.models.deletion.PROTECT, related_name='quota_firm_allocations', to='core.exportfirm')),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='export.quotaissuance')),
            ],
            options={
                'db_table': '[export].[quota_issuance_firm_allocations]',
                'ordering': ['export_firm__name_en'],
            },
        ),
        migrations.DeleteModel(
            name='QuotaAllocation',
        ),
        migrations.AddConstraint(
            model_name='quotaissuancefirmallocation',
            constraint=models.UniqueConstraint(fields=('issuance', 'export_firm'), name='uq_issuance_firm'),
        ),
        migrations.AddConstraint(
            model_name='quotaissuancefirmallocation',
            constraint=models.CheckConstraint(condition=models.Q(('kg_quota__gt', 0)), name='chk_issuance_alloc_gt0'),
        ),
    ]
