# Generated by Django 5.1.15 on 2026-03-30 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0009_add_constraints_and_fix_trucks_calc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('transition', 'Status transition'), ('create', 'Created'), ('update', 'Updated')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('object_repr', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quota_80', 'Quota 80%'), ('quota_90', 'Quota 90%'), ('quota_95', 'Quota 95%'), ('quota_100', 'Quota 100%'), ('overdue', 'Overdue shipment')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
