# Generated by Django 5.1.15 on 2026-04-03 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domesticbuyer'),
        ('export', '0010_add_notification_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='core.greenhouseblock')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='block_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_block_manager_assignments',
                'ordering': ['user', 'block__code'],
                'constraints': [models.UniqueConstraint(fields=('user', 'block'), name='uq_block_manager_assignment')],
            },
        ),
    ]
