# Generated by Django 5.1.15 on 2026-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0011_shipment_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='loading_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
