# Generated by Django 5.1.15 on 2026-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0012_fix_field_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customs_clearance',
            field=models.CharField(blank=True, help_text='Row 5: ✓ approved, → in_progress, — not_started', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='documents_status',
            field=models.CharField(blank=True, help_text='Row 6: ok, missing, in_progress', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='harvest_status',
            field=models.CharField(blank=True, help_text='Row 14: ok, harvesting, not_ready', max_length=20, null=True),
        ),
    ]
