# Generated by Django 5.1.15 on 2026-05-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0014_add_shipment_column_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sales_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
