# Generated by Django 5.1.15 on 2026-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0016_hide_cargo_code_sheet_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
