# Generated by Django 5.1.15 on 2026-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0017_add_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentblocksource',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
