# Generated by Django 5.1.15 on 2026-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0017_shipment_draft_status_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('quota_80', 'Quota 80%'), ('quota_90', 'Quota 90%'), ('quota_95', 'Quota 95%'), ('quota_100', 'Quota 100%'), ('overdue', 'Overdue shipment'), ('action_required', 'Action required'), ('plan_submitted', 'Plan submitted'), ('plan_approved', 'Plan approved'), ('plan_rejected', 'Plan rejected')], max_length=30),
        ),
    ]
