# Generated by Django 5.1.15 on 2026-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0018_add_blocksource_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vehicle_live_status',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True),
        ),
    ]
