# Generated by Django 5.1.15 on 2026-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0019_add_vehicle_live_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='additional_notes_arap',
            field=models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
