# Generated by Django 5.1.15 on 2026-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0021_remap_retired_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstatuslog',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
