# Generated by Django 5.1.15 on 2026-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0022_add_status_log_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_value',
            field=models.CharField(blank=True, default='', help_text='Mirrors TaskRule.target_value at task-create time', max_length=64),
        ),
        migrations.AddField(
            model_name='taskrule',
            name='target_value',
            field=models.CharField(blank=True, default='', help_text='For FIELD_EQUALS rules: the value to compare against (string-cast)', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_rule',
            field=models.CharField(choices=[('all_fields_filled', 'All target fields filled'), ('any_field_filled', 'Any target field filled'), ('field_equals', 'Target field equals a specific value'), ('manual_done', 'Marked done manually')], default='all_fields_filled', max_length=24),
        ),
        migrations.AlterField(
            model_name='taskrule',
            name='completion_rule',
            field=models.CharField(choices=[('all_fields_filled', 'All target fields filled'), ('any_field_filled', 'Any target field filled'), ('field_equals', 'Target field equals a specific value'), ('manual_done', 'Marked done manually')], default='all_fields_filled', max_length=24),
        ),
    ]
