# Generated by Django 5.1.15 on 2026-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0023_task_field_equals'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sheet_position',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
