# Generated by Django 5.1.15 on 2026-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0025_add_shipment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='transport_docs_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
