# Generated by Django 5.1.15 on 2026-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0027_auditlog_field_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetrowsetting',
            name='triggered_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], default='', help_text='If set, only users with this role may edit this row (AND must have field perm).', max_length=30),
        ),
    ]
