# Generated by Django 5.1.15 on 2026-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0027_unhide_cargo_code_sheet_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_label_color',
            field=models.CharField(blank=True, help_text='Row label text colour as #RRGGBB hex string. Applied to the field-name label in the left frozen column.', max_length=7),
        ),
    ]
