# Generated by Django 5.1.15 on 2026-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0028_alter_sheetrowsetting_triggered_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('quota_80', 'Quota 80%'), ('quota_90', 'Quota 90%'), ('quota_95', 'Quota 95%'), ('quota_100', 'Quota 100%'), ('overdue', 'Overdue shipment'), ('action_required', 'Action required'), ('plan_submitted', 'Plan submitted'), ('forecast_nudge', 'Forecast nudge (T1)'), ('forecast_handoff', 'Forecast handoff to warehouse_chief (T2)'), ('forecast_escalation', 'Forecast escalation — urgent (T3)'), ('plan_deadline_reminder', 'Plan deadline reminder (P1)'), ('plan_late', 'Plan late (P2)'), ('plan_critical_late', 'Plan critical-late (P3)'), ('plan_approved', 'Plan approved (deprecated)'), ('plan_rejected', 'Plan rejected (deprecated)'), ('mention', 'Mention'), ('task_assigned', 'Task assigned'), ('task_done', 'Task done')], max_length=30),
        ),
    ]
