# Generated by Django 5.1.15 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    # Re-parented from 0030_harvest_date_to_text → 0029 so this role-choices
    # migration does not depend on the (separately-tracked) harvest-date work.
    # 0031 only AlterFields sheetrowroletrigger.role choices — no schema overlap
    # with 0030. 0032 (already on origin) depends on this node by name, so the
    # rename is transparent to it.
    dependencies = [
        ('export', '0029_rename_style_label_color_to_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetrowroletrigger',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('loading_dept_head_deputy', 'Loading Dept Deputy'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], max_length=30),
        ),
    ]
