# Generated by Django 5.1.15, extended for Sheet Control v2 (ADR-0008, ADR-0009, ADR-0010)
#
# Migration 0031 — additive fields on SheetRowSetting + data steps
#
# Data steps:
#   1. Backfill display_order from row_number × 1024 (ADR-0007)
#   2. Convert inactive-user locks → is_locked=True, triggered_user=None (ADR-0010)
#
# NOTE: triggered_role removal is in 0032 (after SheetRowRoleTrigger is populated).
# This migration ONLY adds new columns and runs data transformations on SheetRowSetting.
# New child models SheetRowRoleTrigger and SheetRowUserPermission are in 0032/0033.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_display_order(apps, schema_editor):
    """Set display_order = row_number * 1024 for every existing SheetRowSetting row."""
    SheetRowSetting = apps.get_model('export', 'SheetRowSetting')
    rows = list(SheetRowSetting.objects.order_by('row_number').only('id', 'row_number'))
    if not rows:
        print('\n  [0031] No SheetRowSetting rows to backfill.')
        return
    for row in rows:
        row.display_order = (row.row_number or 0) * 1024
    SheetRowSetting.objects.bulk_update(rows, ['display_order'], batch_size=500)
    print(f'\n  [0031] display_order backfilled for {len(rows)} SheetRowSetting rows.')


def migrate_inactive_user_locks(apps, schema_editor):
    """Convert rows whose triggered_user is inactive into is_locked=True rows.

    Old semantics: inactive triggered_user → row locked for everyone.
    New semantics: is_locked=True + no triggered_user (ADR-0010).
    """
    SheetRowSetting = apps.get_model('export', 'SheetRowSetting')
    rows_to_convert = list(
        SheetRowSetting.objects.filter(
            triggered_user__isnull=False,
            triggered_user__is_active=False,
        )
    )
    if not rows_to_convert:
        print('\n  [0031] No inactive-user locks to convert.')
        return
    for row in rows_to_convert:
        row.is_locked = True
        row.triggered_user_id = None
    SheetRowSetting.objects.bulk_update(
        rows_to_convert, ['is_locked', 'triggered_user_id'], batch_size=500,
    )
    print(
        f'\n  [0031] Converted {len(rows_to_convert)} inactive-user-lock rows '
        f'→ is_locked=True, triggered_user=None.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0030_alter_notification_kind_stage2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Meta change: set ordering ──────────────────────────────────────
        migrations.AlterModelOptions(
            name='sheetrowsetting',
            options={'ordering': ['display_order']},
        ),

        # ── New display fields ─────────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sparse integer (step 1024). Controls row order in Sheet view.'),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Hidden rows are excluded from the /sheet/ payload entirely.'),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When True, only users in role_triggers or active user_permissions may edit. Superuser/admin/director bypass this lock always.'),
        ),

        # ── Localized labels ───────────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='label_tk',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='Row label in Turkmen. Fallback: i18n file → field_key raw.', max_length=120),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='label_ru',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='Row label in Russian.', max_length=120),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='label_en',
            field=models.CharField(blank=True, help_text='Row label in English.', max_length=120),
        ),

        # ── Localized descriptions ─────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='description_tk',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='Tooltip description in Turkmen.', max_length=255),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='description_ru',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', help_text='Tooltip description in Russian.', max_length=255),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='description_en',
            field=models.CharField(blank=True, help_text='Tooltip description in English.', max_length=255),
        ),

        # ── Style columns ──────────────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Column width in pixels. Valid range: 50–500.', null=True),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_align',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text="Text alignment: 'left', 'center', or 'right'.", max_length=8),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_color',
            field=models.CharField(blank=True, help_text='Background colour as #RRGGBB hex string.', max_length=7),
        ),

        # ── Concurrency / version ──────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented on every save(). Used for optimistic locking in PATCH.'),
        ),

        # ── Soft-delete columns ────────────────────────────────────────────
        migrations.AddField(
            model_name='sheetrowsetting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set to now() on soft-delete. Null = active.', null=True),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # ── Alter existing fields to match v2 semantics ────────────────────
        migrations.AlterField(
            model_name='sheetrowsetting',
            name='field_key',
            field=models.CharField(help_text='Matches field_key in DEFAULT_SHEET_ROWS. Immutable after creation.', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='sheetrowsetting',
            name='row_number',
            field=models.PositiveSmallIntegerField(help_text='Original display ordinal from DEFAULT_SHEET_ROWS. Superseded by display_order.'),
        ),
        migrations.AlterField(
            model_name='sheetrowsetting',
            name='triggered_user',
            field=models.ForeignKey(blank=True, help_text='When set, this specific user has edit rights (if active). Semantics changed from v1: this is now an exception grant, not a lock. Inactive user treated as if not set (ADR-0010).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_rows_triggered', to=settings.AUTH_USER_MODEL),
        ),

        # ── Data step 1: backfill display_order ────────────────────────────
        migrations.RunPython(
            backfill_display_order,
            reverse_code=migrations.RunPython.noop,
        ),

        # ── Data step 2: convert inactive-user locks to is_locked=True ─────
        migrations.RunPython(
            migrate_inactive_user_locks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
