# Generated by Django 5.1.15 on 2026-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0031_add_loading_dept_head_deputy_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_font_family',
            field=models.CharField(blank=True, choices=[('dm_sans', 'DM Sans'), ('inter', 'Inter'), ('mono', 'Monospace'), ('serif', 'Serif')], help_text='Cell text font-family key (dm_sans/inter/mono/serif). Blank = inherit the sheet default font.', max_length=10),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_font_style',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Italic')], help_text="Cell text style. Blank = upright. Set 'italic' to italicize this row's data cells.", max_length=6),
        ),
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_font_weight',
            field=models.CharField(blank=True, choices=[('bold', 'Bold'), ('normal', 'Normal')], help_text="Cell text weight. Blank = bold (the sheet default). Set 'normal' to un-bold this row's data cells.", max_length=6),
        ),
        migrations.AlterField(
            model_name='sheetrowsetting',
            name='style_font_color',
            field=models.CharField(blank=True, help_text="Cell text colour as #RRGGBB hex string. Applied to value text inside this row's data cells across all shipments. Overrides the auto WCAG-contrast color picked from the cell background.", max_length=7),
        ),
    ]
