# Generated by Django 5.1.15 on 2026-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0032_sheetrowsetting_style_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrowsetting',
            name='style_font_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cell text font size in pixels (scaled by zoom on render). Valid range: 8–28. Null = inherit the sheet default (11px).', null=True),
        ),
    ]
