# Generated by Django 5.1.15 on 2026-06-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0030_harvest_date_to_text'),
        ('export', '0034_notification_feedback_kinds'),
    ]

    operations = [
    ]
