# Generated by Django 5.1.15 on 2026-06-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0035_merge_20260611_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('shipment', 'Shipment task'), ('weekly_plan', 'Weekly harvest-plan task')], db_index=True, default='shipment', help_text='Task category. shipment = generated by the status rule engine; weekly_plan = per-manager weekly harvest-plan to-do', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Frontend route the task card navigates to (e.g. weekly_plan grid)', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='scope_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ISO week number this task covers (weekly_plan tasks)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scope_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ISO year this task covers (weekly_plan tasks)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Parent shipment; null for non-shipment tasks (e.g. weekly_plan)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='export.shipment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.CharField(db_index=True, help_text="Shipment status when the task was generated; 'weekly_plan' for weekly-plan tasks", max_length=32),
        ),
    ]
