# Generated by Django 5.1.15 on 2026-06-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0036_task_kind_task_link_task_scope_week_task_scope_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='currency',
            field=models.CharField(default='KZT', max_length=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='net_income_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_expenses_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_sales_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='weight_loaded_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SalesReportExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOM_ROSHOD', 'Tom Roshod (Production cost deduction)'), ('NAKLIYE', 'Nakliye (Transport/delivery fee)'), ('BAZAR_ROSHOD', 'Bazar Roshod (Market fee)'), ('INTERES', 'Interes (Commission/interest)'), ('UZBEK_FURA_AWANS', 'Uzbek Fura Awans (Uzbek truck advance)'), ('DOZWOL', 'Dozwol (Permit fee)'), ('ANALIZ', 'Analiz (Lab analysis fee)'), ('PROSTOY', 'Prostoy (Demurrage)'), ('PERESEPKA', 'Peresepka (Reloading fee)'), ('ARAP', 'Arap (Arab brokerage)'), ('KASPIY_KOMIS', 'Kaspiy Komis (Caspian commission)'), ('UZBEK_FURA_SOLYARKA', 'Uzbek Fura Solyarka (Uzbek truck fuel)'), ('NDS', 'NDS (VAT)'), ('SBOR', 'Sbor (Levy/collection fee)'), ('UZB_KAZ_POST', 'Uzb-Kaz Post (UZ-KZ postal/border fee)'), ('UZB_KAZ_NAKLIYE', 'Uzb-Kaz Nakliye (UZ-KZ transport)'), ('UZBEK_TAM', 'Uzbek Tam (Uzbek customs)'), ('MOI', 'Moi (Security/police fee)'), ('DOSMOTR', 'Dosmotr (Inspection fee)'), ('PEREWOT', 'Perewot (Translation fee)'), ('OTHER', 'Other')], max_length=32)),
                ('label_raw', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=120, null=True)),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=14)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='export.salesreport')),
            ],
            options={
                'db_table': 'export_sales_report_expenses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReportLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('product_name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_local', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=14)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='export.salesreport')),
            ],
            options={
                'db_table': 'export_sales_report_line_items',
                'ordering': ['line_number'],
            },
        ),
    ]
