# Generated by Django 5.1.15 on 2026-06-20 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0037_salesreport_currency_salesreport_exchange_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('GUMRUKLEME', 'Customs clearance (per truck)'), ('KARANTIN', 'Quarantine fee'), ('CT1', 'CT-1 certificate of origin'), ('FITO', 'Phytosanitary certificate'), ('ANALIZ', 'Lab analysis'), ('PASPORT_SDELKA', 'Deal passport (bank)'), ('PLATYOSKA', 'Payment order registration'), ('DOC_POST', 'Document postage'), ('YUZLENME_HAT', 'Reference letter'), ('GUMRUK_AMAL', 'Customs operation fee'), ('BORDER_RETURN', 'Truck returned (border closed)'), ('SERTNAMA', 'Contract fee'), ('OTHER', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TMT', max_length=10)),
                ('cargo_code_raw', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=60, null=True)),
                ('route_label', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=120, null=True)),
                ('label_raw', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=255, null=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, help_text='Unit count for batch fees, e.g. 19 for "19 AD KARANTIN".', null=True)),
                ('notes', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customs_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_expenses', to='export.shipment')),
            ],
            options={
                'db_table': 'export_customs_expenses',
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['shipment'], name='customs_exp_shipment_idx'), models.Index(fields=['category'], name='customs_exp_category_idx'), models.Index(fields=['expense_date'], name='customs_exp_date_idx')],
            },
        ),
    ]
