# Generated by Django 5.1.15 on 2026-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0038_customsexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsexpense',
            name='cargo_code_raw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
