# Generated by Django 5.1.15 on 2026-06-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0043_alter_notification_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsexpense',
            old_name='shipment_code_raw',
            new_name='export_code_raw',
        ),
    ]
