# Generated by Django 5.1.15 on 2026-06-23 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_export_code_field_permission'),
        ('export', '0044_rename_shipment_code_raw_customsexpense_export_code_raw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_coverage', to='core.country')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_coverage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_sales_rep_coverage',
                'ordering': ['country'],
                'unique_together': {('sales_rep', 'country')},
            },
        ),
    ]
