# Generated by Django 5.1.15 on 2026-06-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0047_relabel_rejected_weight_to_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_tk', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=200)),
                ('name_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'export_expense_categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='salesreportexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_rows', to='export.expensecategory'),
        ),
    ]
