# Generated by Django 5.1.15 on 2026-06-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seed_country_currency'),
        ('export', '0049_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scope_block',
            field=models.ForeignKey(blank=True, help_text='Block this weekly_plan task covers — one task per (manager, block) per ISO week. SET_NULL (not PROTECT) so deleting a block is never blocked by an ephemeral reminder task; a null-block weekly_plan task is simply skipped by the resolver. Always null for shipment tasks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.greenhouseblock'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('shipment', 'Shipment task'), ('weekly_plan', 'Weekly harvest-plan task')], db_index=True, default='shipment', help_text='Task category. shipment = generated by the status rule engine; weekly_plan = per-(manager, block) weekly harvest-plan to-do', max_length=16),
        ),
    ]
