# Generated by Django 5.1.15 on 2026-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0050_task_scope_block_alter_task_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('shipment', 'Shipment task'), ('weekly_plan', 'Weekly harvest-plan task'), ('local_sell_plan', 'Local sell-plan task')], db_index=True, default='shipment', help_text='Task category. shipment = generated by the status rule engine; weekly_plan = per-(manager, block) weekly harvest-plan to-do', max_length=16),
        ),
    ]
