# Generated by Django 5.1.15 on 2026-07-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0052_packingpreset_shipment_packing_preset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=120
                    ),
                ),
                ("weights", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "export_split_template",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
