# Generated by Django 5.1.15 on 2026-07-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0053_splittemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=120
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("tomato", "Tomato"), ("pepper", "Pepper")],
                        default="tomato",
                        max_length=10,
                    ),
                ),
                (
                    "net_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("box_count", models.IntegerField(blank=True, null=True)),
                (
                    "pallet_count",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "pallet_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "export_packing_template",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackingTemplateShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_order", models.IntegerField(default=0)),
                (
                    "net_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("box_count", models.IntegerField(blank=True, null=True)),
                (
                    "pallet_count",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "pallet_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="export.packingtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "export_packing_template_share",
                "ordering": ["share_order"],
            },
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="packing_preset",
        ),
        migrations.DeleteModel(
            name="SplitTemplate",
        ),
        migrations.AddField(
            model_name="shipment",
            name="packing_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="export.packingtemplate",
            ),
        ),
        migrations.DeleteModel(
            name="PackingPreset",
        ),
    ]
