# Generated by Django 5.1.15 on 2026-07-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_truckdestination_is_default"),
        ("export", "0055_cascade_orphan_replies"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyDestinationSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="week_selections",
                        to="core.truckdestination",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        db_column="season_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.season",
                    ),
                ),
            ],
            options={
                "db_table": "export_weekly_destination_selections",
                "ordering": ["destination__sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "week_number", "year", "destination"),
                        name="uq_weekly_dest_selection",
                    )
                ],
            },
        ),
    ]
