# Generated by Django 5.1.15 on 2026-07-21 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0056_weeklydestinationselection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User credited with completing this task; null when no user was in scope.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
