# Generated by Django 5.1.15 on 2026-08-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_season_closed_at_season_closed_by_and_more"),
        ("export", "0057_task_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotaissuance",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quota_issuances",
                to="core.season",
            ),
        ),
    ]
