# Generated by Django 5.1.15 on 2026-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0058_quotaissuance_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessNodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=40, unique=True)),
                (
                    "label",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=120
                    ),
                ),
                ("route", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "export_process_node_links",
                "ordering": ["node_id"],
            },
        ),
    ]
