# Generated by Django 5.1.15 on 2026-08-06 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0060_seed_process_node_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processnodelink",
            name="route",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                validators=[
                    django.core.validators.RegexValidator(
                        message='route must be blank or an in-app absolute path (e.g. "/export/plan").',
                        regex="^/([A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*/?)?$",
                    )
                ],
            ),
        ),
    ]
