# Generated by Django 5.1.15 on 2026-08-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0061_alter_processnodelink_route_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentblocksource",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
