# Generated by Django 5.1.15 on 2026-08-24 08:37
"""
Adds SheetRowSetting.role_group (admin override for the Sheet's role-block
grouping, frontend components/sheet/sheetRoleBlocks.ts) and backfills it for
the default rows.

The backfill mapping is the SAME who-key -> role table already confirmed
with the user 2026-06-02 in
apps.export.management.commands.backfill_sheet_row_defaults.WHO_TO_ROLE
(there it seeds role_triggers, a different field with a different purpose —
edit access past a lock, not visual grouping). Duplicated here as a plain
literal because a migration must not import a management command module.
Keep this, that command's WHO_TO_ROLE, and the frontend's WHO_KEY_ROLE in
sheetRoleBlocks.ts in sync if the org chart changes.

Update-only and idempotent: only touches rows whose role_group is still
blank, and only rows that already exist — does not create SheetRowSetting
rows (that stays backfill_sheet_row_defaults's job).
"""
from django.db import migrations, models

# who-key slug (DEFAULT_SHEET_ROWS[*]['default_who_key'] minus the
# 'sheet.who.' prefix) -> ROLE_CHOICES code. 'quality' has no matching role
# and is intentionally omitted, same as WHO_TO_ROLE.
_WHO_SLUG_TO_ROLE = {
    'gadam': 'export_manager',
    'aganazar': 'export_manager',
    'soltanmyrat': 'loading_dept_head',
    'sirin': 'document_team',
    'sulgun': 'document_team',
    'arap': 'sales_rep',
    'malik': 'transport',
    'haltac': 'transport',
    'mergen': 'transport',
    'babageldi': 'finansist',
    'logist': 'transport',
    'transport': 'transport',
}


def backfill_role_group(apps, schema_editor):
    from apps.export.sheet_rows import DEFAULT_SHEET_ROWS

    SheetRowSetting = apps.get_model('export', 'SheetRowSetting')
    existing = {s.field_key: s for s in SheetRowSetting.objects.filter(role_group='')}
    if not existing:
        return

    to_update = []
    for row in DEFAULT_SHEET_ROWS:
        setting = existing.get(row['field_key'])
        if setting is None:
            continue
        who_slug = row['default_who_key'].rsplit('.', 1)[-1]
        role = _WHO_SLUG_TO_ROLE.get(who_slug)
        if role is None:
            continue
        setting.role_group = role
        to_update.append(setting)

    if to_update:
        SheetRowSetting.objects.bulk_update(to_update, ['role_group'], batch_size=500)


def clear_role_group(apps, schema_editor):
    SheetRowSetting = apps.get_model('export', 'SheetRowSetting')
    SheetRowSetting.objects.filter(
        role_group__in=list(set(_WHO_SLUG_TO_ROLE.values())),
    ).update(role_group='')


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0062_alter_shipmentblocksource_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetrowsetting",
            name="role_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("export_manager", "Export Manager"),
                    ("loading_dept_head", "Loading Dept Head"),
                    ("loading_dept_head_deputy", "Loading Dept Deputy"),
                    ("warehouse_chief", "Warehouse Chief"),
                    ("weight_master", "Weight Master"),
                    ("document_team", "Document Team"),
                    ("transport", "Transport"),
                    ("sales_rep", "Sales Rep"),
                    ("finansist", "Finansist"),
                    ("director", "Director"),
                    ("accountant", "Accountant"),
                    ("greenhouse_manager", "Greenhouse Manager"),
                    ("seller", "Seller"),
                    ("boss", "Boss"),
                ],
                help_text="Which role-block this row groups under in the Sheet. Blank = use the frontend default mapping (or none, for a row with no default).",
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_role_group, reverse_code=clear_role_group),
    ]
