# Generated by Django 5.1.15 on 2026-08-28 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0063_sheet_row_role_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetCellColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text='Sheet row field_key this color applies to (e.g. "country").',
                        max_length=64,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Background colour as #RRGGBB hex string.",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_colors",
                        to="export.shipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "export_sheet_cell_color",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment", "field_key"), name="uq_sheet_cell_color"
                    )
                ],
            },
        ),
    ]
