# Generated by Django 5.1.15 on 2026-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0066_fill_blank_sheet_row_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="driver_2_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_2_name",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_2_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="truck_head_2_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="truck_plate_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
