# Generated by Django 5.1.15 on 2026-09-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0067_shipment_second_rig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="rejected_weight_kg",
            new_name="weight_to_load_kg",
        ),
    ]
