# Generated by Django 5.1.15 on 2026-09-17 07:10
"""Customs expense categories become data so cashiers can add new ones.

The 13 former TextChoices codes are seeded as core.ShipmentOptionType rows under
category='customs_expense'. label_en keeps the old choices label, so the API's
category_display is unchanged for existing rows. Dropping `choices` is state-only.
"""

from django.db import migrations, models

CATEGORY = 'customs_expense'

# (code, label_tk, label_ru, label_en)
SEED = [
    ('GUMRUKLEME', 'Gümrüklemek', 'Таможенное оформление', 'Customs clearance (per truck)'),
    ('KARANTIN', 'Karantin tölegi', 'Карантинный сбор', 'Quarantine fee'),
    ('CT1', 'ST-1 güwänamasy', 'Сертификат СТ-1', 'CT-1 certificate of origin'),
    ('FITO', 'Fitosanitariýa güwänamasy', 'Фитосанитарный сертификат', 'Phytosanitary certificate'),
    ('ANALIZ', 'Laboratoriýa seljermesi', 'Лабораторный анализ', 'Lab analysis'),
    ('PASPORT_SDELKA', 'Geleşik pasporty', 'Паспорт сделки', 'Deal passport (bank)'),
    ('PLATYOSKA', 'Töleg tabşyrygy hasaba alynmagy', 'Регистрация платёжного поручения',
     'Payment order registration'),
    ('DOC_POST', 'Resminama poçtasy', 'Пересылка документов', 'Document postage'),
    ('YUZLENME_HAT', 'Ýüzlenme haty', 'Справочное письмо', 'Reference letter'),
    ('GUMRUK_AMAL', 'Gümrük amaly tölegi', 'Таможенный операционный сбор', 'Customs operation fee'),
    ('BORDER_RETURN', 'Maşyn serhetden yza dolandy', 'Авто вернулось (граница закрыта)',
     'Truck returned (border closed)'),
    ('SERTNAMA', 'Şertnama tölegi', 'Контрактный сбор', 'Contract fee'),
    ('OTHER', 'Beýleki', 'Прочее', 'Other'),
]


def seed_categories(apps, schema_editor):
    Option = apps.get_model('core', 'ShipmentOptionType')
    for index, (code, label_tk, label_ru, label_en) in enumerate(SEED, start=1):
        Option.objects.get_or_create(
            category=CATEGORY,
            code=code,
            defaults={
                'label_tk': label_tk,
                'label_ru': label_ru,
                'label_en': label_en,
                'sort_order': index * 10,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_worklog_team_kpi_page_perms"),
        ("export", "0069_rename_weight_to_load_field_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsexpense",
            name="category",
            field=models.CharField(max_length=32),
        ),
        # Reverse leaves the rows: they may already be referenced by added categories' expenses.
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
