# Generated by Django 5.1.15 on 2026-09-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0070_customs_expense_categories_as_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("quota_80", "Quota 80%"),
                    ("quota_90", "Quota 90%"),
                    ("quota_95", "Quota 95%"),
                    ("quota_100", "Quota 100%"),
                    ("overdue", "Overdue shipment"),
                    ("action_required", "Action required"),
                    ("forecast_nudge", "Forecast nudge"),
                    ("forecast_handoff", "Forecast handoff"),
                    ("forecast_escalation", "Forecast escalation"),
                    ("plan_deadline_reminder", "Plan deadline reminder"),
                    ("plan_late", "Plan late"),
                    ("plan_critical_late", "Plan critical-late"),
                    ("weekly_plan_summary", "Weekly plan summary"),
                    ("mention", "Mention"),
                    ("task_assigned", "Task assigned"),
                    ("task_done", "Task done"),
                    ("feedback_resolved", "Feedback resolved"),
                    ("feedback_rejected", "Feedback rejected"),
                    ("stuck_8d", "Stuck shipment — 8 days"),
                    ("stuck_15d", "Stuck shipment — 15 days"),
                    ("stuck_30d", "Stuck shipment — 30+ days"),
                    ("plan_submitted", "Plan submitted (deprecated)"),
                    ("plan_approved", "Plan approved (deprecated)"),
                    ("plan_rejected", "Plan rejected (deprecated)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shipment", "Shipment task"),
                    ("weekly_plan", "Weekly harvest-plan task"),
                    ("local_sell_plan", "Local sell-plan task"),
                    ("truck_allocation", "Weekly truck-allocation task"),
                ],
                db_index=True,
                default="shipment",
                help_text="Task category. shipment = generated by the status rule engine; weekly_plan = per-(manager, block) weekly harvest-plan to-do",
                max_length=16,
            ),
        ),
    ]
