# Generated by Django 5.1.15 on 2026-09-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0072_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheetrowroletrigger",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("export_manager", "Export Manager"),
                    ("loading_dept_head", "Loading Dept Head"),
                    ("loading_dept_head_deputy", "Loading Dept Deputy"),
                    ("warehouse_chief", "Warehouse Chief"),
                    ("weight_master", "Weight Master"),
                    ("document_team", "Document Team"),
                    ("transport", "Transport"),
                    ("sales_rep", "Sales Rep"),
                    ("finansist", "Finansist"),
                    ("director", "Director"),
                    ("accountant", "Accountant"),
                    ("greenhouse_manager", "Greenhouse Manager"),
                    ("seller", "Seller"),
                    ("quality_inspector", "Quality Inspector"),
                    ("boss", "Boss"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sheetrowsetting",
            name="role_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("export_manager", "Export Manager"),
                    ("loading_dept_head", "Loading Dept Head"),
                    ("loading_dept_head_deputy", "Loading Dept Deputy"),
                    ("warehouse_chief", "Warehouse Chief"),
                    ("weight_master", "Weight Master"),
                    ("document_team", "Document Team"),
                    ("transport", "Transport"),
                    ("sales_rep", "Sales Rep"),
                    ("finansist", "Finansist"),
                    ("director", "Director"),
                    ("accountant", "Accountant"),
                    ("greenhouse_manager", "Greenhouse Manager"),
                    ("seller", "Seller"),
                    ("quality_inspector", "Quality Inspector"),
                    ("boss", "Boss"),
                ],
                help_text="Which role-block this row groups under in the Sheet. Blank = use the frontend default mapping (or none, for a row with no default).",
                max_length=30,
            ),
        ),
    ]
