# Generated by Django 5.1.15 on 2026-09-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0074_quality_inspector_sheet_row"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("azyk_maglumatnama", "Azyk maglumatnamasy"),
                            ("suriji_gozukdiriji", "Sürüji gözükdirijisi"),
                            ("hil_sertifikaty", "Hil sertifikaty"),
                            ("kalibrowka_analiz", "Kalibrowka analizi"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(upload_to="quality_certificates/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quality_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="export.qualitydocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_quality_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "export_quality_certificates",
                "ordering": ["doc_type", "-uploaded_at"],
            },
        ),
    ]
