# Generated by Django 5.1.15 on 2026-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0075_quality_certificate_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualitycertificate",
            name="original_filename",
            field=models.CharField(
                db_collation="Cyrillic_General_CI_AS", max_length=255
            ),
        ),
    ]
