# Generated by Django 5.1.15 on 2026-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0076_quality_certificate_filename_collation"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="driver_2_passport_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_2_passport_serial",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_passport_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_passport_serial",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
