# Generated by Django 5.1.15 on 2026-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0077_gapy_driver_passports"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cancelled_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Cancelled by a user"),
                    ("shipment_cancelled", "Shipment was cancelled"),
                    ("rule_mismatch", "Rule no longer applies"),
                    ("rule_deactivated", "Rule was deactivated"),
                ],
                default="",
                help_text="Why this task was cancelled; blank on tasks that were never cancelled and on rows cancelled before 2026-09 (unknown, not 'manual').",
                max_length=24,
            ),
        ),
    ]
