# Generated by Django 5.1.15 on 2026-09-25 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_country_border_point"),
        ("export", "0079_notification_tasks_changed_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("rule__isnull", False), ("shipment__isnull", False)
                ),
                fields=("shipment", "rule"),
                name="export_task_one_per_shipment_rule",
            ),
        ),
    ]
