# Generated by Django 5.1.15 on 2026-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0082_garawul_role_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="greenhouse_arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
