# Generated by Django 5.1.15 on 2026-09-29 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_seed_garawul_perms"),
        ("export", "0084_notification_gate_arrival_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ack_snapshot",
            field=models.TextField(
                blank=True,
                default="",
                help_text='ASCII "k:v;..." counts snapshot: the review baseline on a truck_allocation task, or what was seen at «Tanyşdym» on alloc_review / transport_plan tasks',
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="scope_date",
            field=models.DateField(
                blank=True,
                help_text="Local day a daily_loading / daily_export task covers",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="cancelled_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Cancelled by a user"),
                    ("shipment_cancelled", "Shipment was cancelled"),
                    ("rule_mismatch", "Rule no longer applies"),
                    ("rule_deactivated", "Rule was deactivated"),
                    ("missed", "Daily task not done on its day"),
                ],
                default="",
                help_text="Why this task was cancelled; blank on tasks that were never cancelled and on rows cancelled before 2026-09 (unknown, not 'manual').",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shipment", "Shipment task"),
                    ("weekly_plan", "Weekly harvest-plan task"),
                    ("local_sell_plan", "Local sell-plan task"),
                    ("truck_allocation", "Weekly truck-allocation task"),
                    ("alloc_review", "Truck-allocation review (plan changed)"),
                    ("transport_plan", "Transport truck planning («Tanyşdym»)"),
                    ("daily_loading", "Daily loading plan (Gaplama)"),
                    ("daily_export", "Daily export plan"),
                ],
                db_index=True,
                default="shipment",
                help_text="Task category. shipment = generated by the status rule engine; weekly_plan = per-(manager, block) weekly harvest-plan to-do",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["daily_loading", "daily_export"])),
                fields=("kind", "scope_date"),
                name="export_task_one_daily_per_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind__in", ["alloc_review", "transport_plan"]),
                    ("state__in", ["open", "in_progress"]),
                ),
                fields=("kind", "scope_year", "scope_week"),
                name="export_task_one_open_ack_per_week",
            ),
        ),
    ]
