# Generated by Django 5.1.15 on 2026-09-29 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_seed_garawul_perms"),
        ("export", "0085_plan_task_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scope_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Greenhouse gate a gate task belongs to — only that location's garawul sees it. Always null for other kinds.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.loadinglocation",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shipment", "Shipment task"),
                    ("weekly_plan", "Weekly harvest-plan task"),
                    ("local_sell_plan", "Local sell-plan task"),
                    ("truck_allocation", "Weekly truck-allocation task"),
                    ("alloc_review", "Truck-allocation review (plan changed)"),
                    ("transport_plan", "Transport truck planning («Tanyşdym»)"),
                    ("daily_loading", "Daily loading plan (Gaplama)"),
                    ("daily_export", "Daily export plan"),
                    ("gate", "Gate guard task"),
                ],
                db_index=True,
                default="shipment",
                help_text="Task category. shipment = generated by the status rule engine; weekly_plan = per-(manager, block) weekly harvest-plan to-do",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "gate")),
                fields=("shipment", "step"),
                name="export_task_one_gate_per_shipment_step",
            ),
        ),
    ]
