# Generated by Django 5.1.15 on 2026-09-29 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0087_seed_greenhouse_arrival_row"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreport",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_reports_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="has_peregruz",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_rule",
            field=models.CharField(
                choices=[
                    ("all_fields_filled", "All target fields filled"),
                    ("any_field_filled", "Any target field filled"),
                    ("field_equals", "Target field equals a specific value"),
                    ("field_set", "Target field has any value (incl. No)"),
                    ("manual_done", "Marked done manually"),
                ],
                default="all_fields_filled",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="taskrule",
            name="completion_rule",
            field=models.CharField(
                choices=[
                    ("all_fields_filled", "All target fields filled"),
                    ("any_field_filled", "Any target field filled"),
                    ("field_equals", "Target field equals a specific value"),
                    ("field_set", "Target field has any value (incl. No)"),
                    ("manual_done", "Marked done manually"),
                ],
                default="all_fields_filled",
                max_length=24,
            ),
        ),
    ]
