# Generated by Django 5.1.15 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0089_task_ack_snapshot_db_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrule",
            name="depends_on",
            field=models.CharField(
                blank=True,
                default="",
                help_text='CSV of title_keys that must be done before this rule creates its task (docs/Tasks.md "after N"). Blank = created at step entry.',
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="taskrule",
            name="effective_from",
            field=models.DateTimeField(
                blank=True,
                help_text="The rule applies only to shipments that entered its step at or after this moment. Set once by seed_task_rules on create.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskrule",
            name="gates_step",
            field=models.BooleanField(
                default=True,
                help_text="False = the task closes itself but never holds the step (join_supply: documents may start before packing).",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_rule",
            field=models.CharField(
                choices=[
                    ("all_fields_filled", "All target fields filled"),
                    ("any_field_filled", "Any target field filled"),
                    ("field_equals", "Target field equals a specific value"),
                    ("field_set", "Target field has any value (incl. No)"),
                    ("confirm", "Button that gates the step"),
                    ("manual_done", "Marked done manually"),
                ],
                default="all_fields_filled",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="taskrule",
            name="completion_rule",
            field=models.CharField(
                choices=[
                    ("all_fields_filled", "All target fields filled"),
                    ("any_field_filled", "Any target field filled"),
                    ("field_equals", "Target field equals a specific value"),
                    ("field_set", "Target field has any value (incl. No)"),
                    ("confirm", "Button that gates the step"),
                    ("manual_done", "Marked done manually"),
                ],
                default="all_fields_filled",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ShipmentDocumentDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_key", models.CharField(max_length=24)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "downloaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_downloads",
                        to="export.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "export_shipment_document_download",
                "indexes": [
                    models.Index(
                        fields=["shipment", "doc_key"], name="export_sdd_ship_doc_idx"
                    )
                ],
            },
        ),
        # Shared DB with beta (old code omits these columns on INSERT) —
        # DB-level defaults, not only Django-side ones (lesson from 0085/0089).
        migrations.RunSQL(
            sql="ALTER TABLE [export_task_rule] ADD CONSTRAINT [DF_export_task_rule_depends_on] DEFAULT N'' FOR [depends_on]; "
                "ALTER TABLE [export_task_rule] ADD CONSTRAINT [DF_export_task_rule_gates_step] DEFAULT 1 FOR [gates_step];",
            reverse_sql="ALTER TABLE [export_task_rule] DROP CONSTRAINT [DF_export_task_rule_depends_on]; "
                        "ALTER TABLE [export_task_rule] DROP CONSTRAINT [DF_export_task_rule_gates_step];",
        ),
    ]
