# Generated by Django 5.1.15 on 2026-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0081_block_source_batch_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="driver_passport_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
