# Generated by Django 5.1.15 on 2026-09-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0090_prep_docs_engine"),
        ("export", "0091_shipment_driver_passport_expiry"),
    ]

    operations = []
