# Generated by Django 5.1.15 on 2026-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0092_merge_prep_docs_and_passport_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="documents_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
