# Generated by Django 5.1.15 on 2026-10-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0094_taskruleassignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="export_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
