"""One-off: dump cross-schema FK map for the schema-collapse refactor.

Reads sys.foreign_keys for tables in the (core, export, greenhouse) schemas
on the currently-configured default DB and writes a markdown report to
docs/MIGRATION_FK_MAP.md plus a topologically sorted table list under the
'## Topological copy order' section. Read-only; safe to run against prod.

Delete this command after the schema collapse is complete.
"""
from collections import defaultdict
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import connection


_FK_QUERY = """
SELECT
    fk.name AS fk_name,
    SCHEMA_NAME(tp.schema_id) + '.' + tp.name AS parent_table,
    SCHEMA_NAME(tr.schema_id) + '.' + tr.name AS referenced_table,
    cp.name AS parent_column,
    cr.name AS referenced_column
FROM sys.foreign_keys fk
INNER JOIN sys.tables tp ON fk.parent_object_id = tp.object_id
INNER JOIN sys.tables tr ON fk.referenced_object_id = tr.object_id
INNER JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
INNER JOIN sys.columns cp ON fkc.parent_column_id = cp.column_id
                         AND fkc.parent_object_id = cp.object_id
INNER JOIN sys.columns cr ON fkc.referenced_column_id = cr.column_id
                         AND fkc.referenced_object_id = cr.object_id
WHERE tp.schema_id IN (SCHEMA_ID('core'), SCHEMA_ID('export'), SCHEMA_ID('greenhouse'))
ORDER BY parent_table, fk_name;
"""

_TABLES_QUERY = """
SELECT SCHEMA_NAME(schema_id) + '.' + name AS qualified
FROM sys.tables
WHERE schema_id IN (SCHEMA_ID('core'), SCHEMA_ID('export'), SCHEMA_ID('greenhouse'))
ORDER BY qualified;
"""


def _topo_sort(tables: list[str], edges: list[tuple[str, str]]) -> list[str]:
    """Return tables ordered so that referenced tables come before their parents.

    edges: list of (parent, referenced) — parent depends on referenced.
    Self-references and cycles are reported alongside the partial order.
    """
    incoming = defaultdict(set)
    outgoing = defaultdict(set)
    for parent, referenced in edges:
        if parent == referenced:
            continue
        incoming[parent].add(referenced)
        outgoing[referenced].add(parent)

    pending = {t for t in tables}
    ordered: list[str] = []
    ready = sorted(t for t in pending if not incoming[t])
    while ready:
        t = ready.pop(0)
        ordered.append(t)
        pending.discard(t)
        for child in sorted(outgoing[t]):
            incoming[child].discard(t)
            if not incoming[child] and child in pending:
                ready.append(child)
                ready.sort()

    cycle_remainder = sorted(pending)
    return ordered + cycle_remainder


class Command(BaseCommand):
    help = "Dump cross-schema FK map to docs/MIGRATION_FK_MAP.md (read-only)."

    def add_arguments(self, parser):
        parser.add_argument(
            '--out',
            default='docs/MIGRATION_FK_MAP.md',
            help='Output path relative to the project root (default: docs/MIGRATION_FK_MAP.md)',
        )

    def handle(self, *args, **opts):
        if connection.vendor != 'microsoft':
            raise CommandError(
                f"This command requires the MSSQL backend; got vendor={connection.vendor}"
            )

        with connection.cursor() as cur:
            cur.execute(_TABLES_QUERY)
            tables = [row[0] for row in cur.fetchall()]
            cur.execute(_FK_QUERY)
            fk_rows = cur.fetchall()

        edges = [(row[1], row[2]) for row in fk_rows]
        ordered = _topo_sort(tables, edges)

        # Build markdown
        lines: list[str] = []
        lines.append('# Migration FK Map — Schema Collapse')
        lines.append('')
        lines.append(
            'Generated by `python manage.py dump_fk_map`. '
            'Read-only against the production DB. Used as input for '
            '`migrate_data_to_flat_schema` (step 7.5 of the schema collapse plan).'
        )
        lines.append('')
        lines.append(f'- Total tables across (core, export, greenhouse): **{len(tables)}**')
        lines.append(f'- Total FK relationships: **{len(fk_rows)}**')
        lines.append('')
        lines.append('## Topological copy order')
        lines.append('')
        lines.append(
            'Order so that a row\'s FK targets are inserted first. Self-references '
            'are ignored. If any tables remain after the topo sort, they form a '
            'cycle and need manual handling.'
        )
        lines.append('')
        for i, t in enumerate(ordered, 1):
            lines.append(f'{i}. `{t}`')
        lines.append('')
        lines.append('## Foreign keys (raw)')
        lines.append('')
        lines.append('| FK Name | Parent Table | Parent Column | -> | Referenced Table | Referenced Column |')
        lines.append('|---|---|---|---|---|---|')
        for fk_name, parent, referenced, parent_col, ref_col in fk_rows:
            lines.append(
                f'| `{fk_name}` | `{parent}` | `{parent_col}` | -> | `{referenced}` | `{ref_col}` |'
            )
        lines.append('')

        out_path = Path(opts['out'])
        if not out_path.is_absolute():
            # Resolve relative to project root (parent of backend/)
            project_root = Path(__file__).resolve().parents[5]
            out_path = project_root / out_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text('\n'.join(lines), encoding='utf-8')

        self.stdout.write(self.style.SUCCESS(f'Wrote {out_path}'))
        self.stdout.write(f'  tables: {len(tables)}')
        self.stdout.write(f'  fks:    {len(fk_rows)}')
        self.stdout.write(f'  ordered (first 5): {ordered[:5]}')
        self.stdout.write(f'  ordered (last 5):  {ordered[-5:]}')
