# Generated by Django 5.1.15 on 2026-04-06 11:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'core')
                    EXEC('CREATE SCHEMA core');
            """,
            reverse_sql="""
                IF EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'core')
                    EXEC('DROP SCHEMA core');
            """,
        ),
        migrations.CreateModel(
            name='BorderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100, unique=True)),
                ('route_description', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('typical_transit_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '[core].[border_points]',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tk', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('name_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': '[core].[countries]',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='DomesticBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '[core].[domestic_buyers]',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_tk', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=200)),
                ('name_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('address_tk', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('address_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('address_en', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_details_tk', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=1000, null=True)),
                ('bank_details_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=1000, null=True)),
                ('bank_details_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('director', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('one_c_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '[core].[export_firms]',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LoadingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': '[core].[loading_locations]',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': '[core].[product_types]',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '[core].[seasons]',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_tk', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('step_order', models.IntegerField()),
                ('required_role', models.CharField(blank=True, max_length=30, null=True)),
                ('phase', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '[core].[shipment_status_types]',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='TomatoVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('avg_fruit_weight_gr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tomato varieties',
                'db_table': '[core].[tomato_varieties]',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager')], default='export_manager', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'sys_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('name_local', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': '[core].[cities]',
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.city')),
                ('default_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.country')),
            ],
            options={
                'db_table': '[core].[customers]',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name_company', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=300)),
                ('name_short', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('bank_details', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=1000, null=True)),
                ('contact_person', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('director_signature', models.FileField(blank=True, null=True, upload_to='import_firms/signatures/')),
                ('director_seal', models.FileField(blank=True, null=True, upload_to='import_firms/seals/')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country')),
            ],
            options={
                'db_table': '[core].[import_firms]',
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='GreenhouseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('area_m2', models.IntegerField(blank=True, null=True)),
                ('section_count', models.IntegerField(blank=True, null=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('season_start_month', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blocks_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_blocks', to='core.greenhouseblock')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='core.loadinglocation')),
                ('variety_main', models.ForeignKey(blank=True, db_column='variety_main_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_blocks', to='core.tomatovariety')),
                ('variety_secondary', models.ForeignKey(blank=True, db_column='variety_secondary_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_blocks', to='core.tomatovariety')),
            ],
            options={
                'db_table': '[core].[greenhouse_blocks]',
                'ordering': ['code'],
            },
        ),
    ]
