# Generated by Django 5.1.15 on 2026-04-06 12:44
#
# Manually rewritten from AddField → RunSQL because mssql-django's schema
# editor builds an incorrect query against sys.default_constraints when
# adding a NOT NULL column with default to a table in a non-dbo schema.
# It looks for t.name = '[core].[export_firms]' (with brackets) instead of
# 'export_firms', finds nothing, then falls back to dropping a constraint
# named after the column, which fails.
#
# The 3-step pattern (ADD as NULL → UPDATE → ALTER to NOT NULL) sidesteps
# the buggy default-constraint cleanup path entirely.
#
# state_operations tells Django's ORM that, logically, these are still
# AddField operations — so the model state matches what models.py declares.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # ── ExportFirm.is_gapy_satys ───────────────────────────────
                "ALTER TABLE [core].[export_firms] ADD [is_gapy_satys] bit NULL;",
                "UPDATE [core].[export_firms] SET [is_gapy_satys] = 0 WHERE [is_gapy_satys] IS NULL;",
                "ALTER TABLE [core].[export_firms] ALTER COLUMN [is_gapy_satys] bit NOT NULL;",
                # ── ImportFirm.is_gapy_satys ───────────────────────────────
                "ALTER TABLE [core].[import_firms] ADD [is_gapy_satys] bit NULL;",
                "UPDATE [core].[import_firms] SET [is_gapy_satys] = 0 WHERE [is_gapy_satys] IS NULL;",
                "ALTER TABLE [core].[import_firms] ALTER COLUMN [is_gapy_satys] bit NOT NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE [core].[import_firms] DROP COLUMN [is_gapy_satys];",
                "ALTER TABLE [core].[export_firms] DROP COLUMN [is_gapy_satys];",
            ],
            state_operations=[
                migrations.AddField(
                    model_name='exportfirm',
                    name='is_gapy_satys',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='importfirm',
                    name='is_gapy_satys',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]