# Generated by Django 5.1.15 on 2026-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfirm',
            name='is_gapy_satys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importfirm',
            name='is_gapy_satys',
            field=models.BooleanField(default=False),
        ),
    ]
