# Generated by Django 5.1.15 on 2026-04-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager')], max_length=30)),
                ('resource_code', models.CharField(max_length=60)),
                ('field_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Role Field Permission',
                'verbose_name_plural': 'Role Field Permissions',
                'db_table': '[core].[role_field_permissions]',
                'unique_together': {('role', 'resource_code', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='RolePagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager')], max_length=30)),
                ('page_code', models.CharField(max_length=60)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role Page Permission',
                'verbose_name_plural': 'Role Page Permissions',
                'db_table': '[core].[role_page_permissions]',
                'unique_together': {('role', 'page_code')},
            },
        ),
        migrations.CreateModel(
            name='RoleResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager')], max_length=30)),
                ('resource_code', models.CharField(max_length=60)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role Resource Permission',
                'verbose_name_plural': 'Role Resource Permissions',
                'db_table': '[core].[role_resource_permissions]',
                'unique_together': {('role', 'resource_code')},
            },
        ),
    ]
