# Generated by Django 5.1.15 on 2026-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grant_loading_dept_head_plan_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstatustype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
