# Generated by Django 5.1.15 on 2026-04-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_shipment_option_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.country'),
        ),
    ]
