# Generated by Django 5.1.15 on 2026-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_crate_type_and_weight_master_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefieldpermission',
            name='role',
            field=models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepagepermission',
            name='role',
            field=models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roleresourcepermission',
            name='role',
            field=models.CharField(choices=[('export_manager', 'Export Manager'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller')], max_length=30),
        ),
    ]
