# Generated by Django 5.1.15 on 2026-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_grant_loading_dept_head_sheet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentoptiontype',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
