# Generated by Django 5.1.15 on 2026-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_color_to_reference_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borderpoint',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['sort_order', 'name_en'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='exportfirm',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='greenhouseblock',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='importfirm',
            options={'ordering': ['sort_order', 'name_company']},
        ),
        migrations.AlterModelOptions(
            name='tomatovariety',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Tomato varieties'},
        ),
        migrations.AddField(
            model_name='borderpoint',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportfirm',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouseblock',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importfirm',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tomatovariety',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
