# Generated by Django 5.1.15 on 2026-06-06 — Phase 3 of the WebSocket feature.
#
# Creates `core_work_sessions` (per-WS-connection rows) and the SQL view
# `core_work_session_daily` that the read-only `WorkSessionDaily` ORM model
# is bound to.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# MSSQL view — sums active_seconds per user per local date. The synthetic
# `id` column gives Django a unique PK to hang the ORM model off.
VIEW_FORWARD = """
CREATE VIEW core_work_session_daily AS
SELECT
    CAST(user_id AS VARCHAR(20)) + '_' + CONVERT(VARCHAR(10), CAST(started_at AS DATE), 23) AS id,
    user_id,
    CAST(started_at AS DATE) AS work_date,
    SUM(active_seconds) AS active_seconds_total,
    MIN(started_at) AS first_seen,
    MAX(COALESCE(ended_at, last_heartbeat_at)) AS last_seen
FROM core_work_sessions
GROUP BY user_id, CAST(started_at AS DATE);
"""

VIEW_REVERSE = "DROP VIEW IF EXISTS core_work_session_daily;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_sort_order_to_reference_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.IntegerField(default=0)),
                ('last_state', models.CharField(default='active', max_length=10)),
                ('tab_session_id', models.CharField(blank=True, default='', max_length=40)),
                ('client_info', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_work_sessions',
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['user', '-started_at'], name='core_work_s_user_id_b9abd6_idx'),
                    models.Index(fields=['ended_at', 'last_heartbeat_at'], name='core_work_s_ended_a_699108_idx'),
                ],
            },
        ),
        # State-only: Django won't try to create the table because managed=False,
        # but the ORM still needs the model declared to issue queries through it.
        migrations.CreateModel(
            name='WorkSessionDaily',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('active_seconds_total', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_work_session_daily',
                'managed': False,
            },
        ),
        # Actual DB view, created after the underlying table exists.
        migrations.RunSQL(VIEW_FORWARD, reverse_sql=VIEW_REVERSE),
    ]
