# Generated by Django 5.1.15 on 2026-04-30 07:03
# Manually edited: added RunPython to seed the GreenhouseConfig singleton (pk=1).

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_greenhouse_config(apps, schema_editor):
    """Create the singleton GreenhouseConfig row with production defaults."""
    GreenhouseConfig = apps.get_model('core', 'GreenhouseConfig')
    GreenhouseConfig.objects.get_or_create(
        pk=1,
        defaults={
            'plan_deadline_weekday': 4,
            'plan_late_until_weekday': 6,
            'plan_critical_late_at_weekday': 0,
            'plan_critical_late_at_time': datetime.time(0, 0),
            'forecast_primary_open': datetime.time(17, 0),
            'forecast_primary_close': datetime.time(18, 0),
            'forecast_fallback_close': datetime.time(9, 0),
            'forecast_same_day_close': datetime.time(23, 59),
            'notification_lead_minutes': 60,
            'truck_capacity_kg': Decimal('18500'),
            'operating_days_bitmask': 0b0111111,
            'timezone_name': 'Asia/Ashgabat',
        },
    )


def reverse_seed_greenhouse_config(apps, schema_editor):
    """Remove the seeded singleton (rollback — leaves table empty)."""
    GreenhouseConfig = apps.get_model('core', 'GreenhouseConfig')
    GreenhouseConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_demote_existing_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_deadline_weekday', models.PositiveSmallIntegerField(default=4, help_text='ISO weekday by which managers must submit plans (4=Friday).')),
                ('plan_late_until_weekday', models.PositiveSmallIntegerField(default=6, help_text='ISO weekday until which late submissions are accepted (6=Sunday).')),
                ('plan_critical_late_at_weekday', models.PositiveSmallIntegerField(default=0, help_text='ISO weekday when plan is considered critically late (0=Monday).')),
                ('plan_critical_late_at_time', models.TimeField(default=datetime.time(0, 0), help_text='Local time on plan_critical_late_at_weekday that triggers critical-late.')),
                ('forecast_primary_open', models.TimeField(default=datetime.time(17, 0), help_text='Local time when the primary forecast window opens (day-before).')),
                ('forecast_primary_close', models.TimeField(default=datetime.time(18, 0), help_text='Local time when the primary forecast window closes (day-before).')),
                ('forecast_fallback_close', models.TimeField(default=datetime.time(9, 0), help_text='Local time of day-of when the fallback window closes.')),
                ('forecast_same_day_close', models.TimeField(default=datetime.time(23, 59), help_text='Local time of day-of when the same-day red-flag window closes.')),
                ('notification_lead_minutes', models.PositiveSmallIntegerField(default=60, help_text='Minutes before a deadline to fire a reminder notification.')),
                ('truck_capacity_kg', models.DecimalField(decimal_places=2, default=Decimal('18500'), help_text='Standard truck capacity in kg; used for Est. Trucks calculation.', max_digits=10)),
                ('operating_days_bitmask', models.PositiveSmallIntegerField(default=63, help_text='Bitmask of operating weekdays: bit 0=Mon … bit 6=Sun. Default 0b0111111 = Mon–Sat.')),
                ('timezone_name', models.CharField(default='Asia/Ashgabat', help_text='IANA timezone name used for local-time window calculations.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '[core].[greenhouse_config]',
            },
        ),
        migrations.CreateModel(
            name='OperatingDayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_holiday', models.BooleanField(default=True, help_text='True = treat this date as non-operating (skip notifications).')),
                ('note', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '[core].[operating_day_exceptions]',
                'ordering': ['date'],
            },
        ),
        # Seed the singleton GreenhouseConfig row with production defaults.
        migrations.RunPython(seed_greenhouse_config, reverse_seed_greenhouse_config),
    ]
