# Generated by Django 5.1.15 on 2026-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clone_loading_dept_head_deputy_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefieldpermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('loading_dept_head_deputy', 'Loading Dept Deputy'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepagepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('loading_dept_head_deputy', 'Loading Dept Deputy'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roleresourcepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('loading_dept_head_deputy', 'Loading Dept Deputy'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('loading_dept_head_deputy', 'Loading Dept Deputy'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], default='export_manager', max_length=30),
        ),
    ]
