# Generated by Django 5.1.15 on 2026-06-24 07:21

from django.db import migrations, models


def seed_name_short(apps, schema_editor):
    """Seed the new shipment short name from the existing document code."""
    ExportFirm = apps.get_model('core', 'ExportFirm')
    firms = list(ExportFirm.objects.all())
    for firm in firms:
        firm.name_short = firm.code
    ExportFirm.objects.bulk_update(firms, ['name_short'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_sales_rep_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfirm',
            name='name_short',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True),
        ),
        migrations.RunPython(seed_name_short, migrations.RunPython.noop),
    ]
