# Generated by Django 5.1.15 on 2026-06-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_exportfirm_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
