# Generated by Django 5.1.15 on 2026-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_grant_departed_at_loading_dept_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckdestination",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
