# Generated by Django 5.1.15 on 2026-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_seed_default_truck_destinations"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="director_seal",
            field=models.FileField(
                blank=True, null=True, upload_to="export_firms/seals/"
            ),
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="director_signature",
            field=models.FileField(
                blank=True, null=True, upload_to="export_firms/signatures/"
            ),
        ),
    ]
