# Generated by Django 5.1.15 on 2026-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_exportfirm_director_seal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="director_tk",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=200,
                null=True,
            ),
        ),
    ]
