# Generated by Django 5.1.15 on 2026-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_exportfirm_director_tk"),
    ]

    operations = [
        migrations.AddField(
            model_name="importfirm",
            name="contact_person_tk",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=200,
                null=True,
            ),
        ),
    ]
