# Generated by Django 5.1.15 on 2026-08-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_boss_process_visibility_perms"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=64)),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                (
                    "response_body",
                    models.TextField(db_collation="Cyrillic_General_CI_AS", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_idempotency_keys",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_idempo_created_6ab1f8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "endpoint", "key"),
                        name="uq_idempotency_user_endpoint_key",
                    )
                ],
            },
        ),
    ]
