# Generated by Django 5.1.15 on 2026-09-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_document_team_export_manager_parity"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="director_stamp",
            field=models.FileField(
                blank=True, null=True, upload_to="export_firms/stamps/"
            ),
        ),
        migrations.AddField(
            model_name="importfirm",
            name="director_stamp",
            field=models.FileField(
                blank=True, null=True, upload_to="import_firms/stamps/"
            ),
        ),
    ]
