# Generated by Django 5.1.15 on 2026-09-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_exportfirm_director_stamp_importfirm_director_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="name_bare_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="name_bare_ru",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="name_bare_tk",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importfirm",
            name="name_bare",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=300,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CompanyLegalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                (
                    "abbr_tk",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=32
                    ),
                ),
                (
                    "abbr_ru",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=32
                    ),
                ),
                ("abbr_en", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "full_tk",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=200
                    ),
                ),
                (
                    "full_ru",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=200
                    ),
                ),
                ("full_en", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "gen_tk",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "gen_ru",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "position_tk",
                    models.CharField(
                        choices=[
                            ("PREFIX", "Before the name"),
                            ("SUFFIX", "After the name"),
                        ],
                        default="SUFFIX",
                        max_length=6,
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(
                        choices=[
                            ("PREFIX", "Before the name"),
                            ("SUFFIX", "After the name"),
                        ],
                        default="PREFIX",
                        max_length=6,
                    ),
                ),
                (
                    "position_en",
                    models.CharField(
                        choices=[
                            ("PREFIX", "Before the name"),
                            ("SUFFIX", "After the name"),
                        ],
                        default="SUFFIX",
                        max_length=6,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        db_table="core_company_legal_type_countries",
                        related_name="legal_types",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "db_table": "core_company_legal_types",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="legal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="export_firms",
                to="core.companylegaltype",
            ),
        ),
        migrations.AddField(
            model_name="importfirm",
            name="legal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_firms",
                to="core.companylegaltype",
            ),
        ),
    ]
