# Generated by Django 5.1.15 on 2026-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_backfill_firm_legal_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="patent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="patent_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="exportfirm",
            name="patent_series",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
