# Generated by Django 5.1.15 on 2026-09-11 07:42

from django.db import migrations, models


# The three loading points that exist today. Seeded here so the Russian CMR
# prints Cyrillic from the first generation rather than waiting on data entry;
# the office corrects the spelling in Django admin, and a re-run never
# overwrites a name someone has already edited.
RU_NAMES = {
    "Dusak": "Дусак",
    "Kaka": "Кака",
    "Owadandepe": "Овадандепе",
}


def seed_russian_names(apps, schema_editor):
    LoadingLocation = apps.get_model("core", "LoadingLocation")
    for name, name_ru in RU_NAMES.items():
        LoadingLocation.objects.filter(name=name, name_ru="").update(name_ru=name_ru)


def unseed_russian_names(apps, schema_editor):
    LoadingLocation = apps.get_model("core", "LoadingLocation")
    for name, name_ru in RU_NAMES.items():
        LoadingLocation.objects.filter(name=name, name_ru=name_ru).update(name_ru="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_sole_proprietor_patent"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadinglocation",
            name="name_ru",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                default="",
                max_length=100,
            ),
        ),
        migrations.RunPython(seed_russian_names, unseed_russian_names),
    ]
