# Generated by Django 5.1.15 on 2026-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_loading_location_name_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="borderpoint",
            name="name_ru",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                default="",
                max_length=100,
            ),
        ),
    ]
