# Generated by Django 5.1.15 on 2026-09-18 05:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_worklog_team_kpi_page_perms"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenhouseconfig",
            name="plan_change_max_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Max ± % a greenhouse manager may revise a started week's plan cell, measured against the cell's week-start baseline.",
                max_digits=5,
            ),
        ),
    ]
