# Generated by Django 5.1.15 on 2026-09-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_greenhouseconfig_plan_change_max_pct"),
        ("core", "0052_tir_takip_page_perms"),
    ]

    operations = []
