# Generated by Django 5.1.15 on 2026-09-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_quality_inspector_tir_takip_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="border_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_countries",
                to="core.borderpoint",
            ),
        ),
    ]
