# Generated by Django 5.1.15 on 2026-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_greenhouseconfig_gaplama_carry_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenhouseblock",
            name="carry_days",
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
