# Generated by Django 5.1.15 on 2026-09-24 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_greenhouseblock_carry_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greenhouseblock",
            name="carry_days",
            field=models.PositiveSmallIntegerField(
                default=7, validators=[django.core.validators.MaxValueValidator(30)]
            ),
        ),
    ]
