# Generated by Django 5.1.15 on 2026-09-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_country_border_point"),
        ("core", "0061_alter_greenhouseblock_carry_days"),
    ]

    operations = []
