# Generated by Django 5.1.15 on 2026-09-25 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_merge_carry_days_and_border_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greenhouseblock",
            name="carry_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
