# Generated by Django 5.1.15 on 2026-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_rename_draft_status_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenhouseconfig",
            name="scan_base_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base URL encoded in printed pallet QR labels, e.g. https://ygt.example. Blank = PLATFORM_URL, then the request host. Printed labels keep the value they were printed with.",
                max_length=200,
            ),
        ),
    ]
