# Generated by Django 5.1.15 on 2026-10-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_loading_dept_truck_pages_and_tir_takip"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfirm",
            name="letterhead",
            field=models.FileField(
                blank=True, null=True, upload_to="export_firms/letterheads/"
            ),
        ),
    ]
