# Generated by Django 5.1.15 on 2026-10-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_exportfirm_letterhead"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="hs_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_ru",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_tk",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tomatovariety",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="varieties",
                to="core.producttype",
            ),
        ),
    ]
