import { useMemo, useState } from 'react';
import { Alert, Card, Select, Space, Switch, Table, Tag, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { useTaskRules } from '@/hooks/useTaskRules';
import type { ITaskRule } from '@/types';

const { Title, Paragraph, Text } = Typography;

/** Colour per completion rule — auto-closing rules read green, manual ones amber. */
const RULE_COLOR: Record<ITaskRule['completion_rule'], string> = {
  all_fields_filled: 'green',
  any_field_filled: 'green',
  field_equals: 'blue',
  manual_done: 'orange',
};

/**
 * The three task kinds that are generated by code, not by a `TaskRule` row.
 *
 * They are absent from `/export/task-rules/` by design — their logic lives in
 * `apps/export/services/{weekly_plan,local_sell_plan,truck_allocation}_tasks.py`
 * and changing one needs a deploy. Listing them here is not optional detail: a
 * `greenhouse_manager` has NO rule in the catalog at all, so the weekly-plan row
 * below is that role's entire queue.
 *
 * Kept as a literal because there is nothing to read it from — the alternative
 * is an endpoint that serves three hardcoded rows.
 */
interface ICodeDrivenKind {
  key: string;
  role: string;
}

const CODE_DRIVEN_KINDS: ICodeDrivenKind[] = [
  { key: 'weekly_plan', role: 'greenhouse_manager' },
  { key: 'local_sell_plan', role: 'seller' },
  { key: 'truck_allocation', role: 'export_manager' },
];

/**
 * Label for a watched or condition field, in the viewer's language.
 *
 * Three sources, most specific first: a task-specific override in
 * `tasks.field_label` (which `SelfBoardShipmentFieldList` also reads, and which
 * is the only place the dotted `quality.*` paths are named), then the shipment
 * field labels the edit drawer already carries in all three languages, then the
 * raw key. Without the second step 26 of the 31 fields these rules watch would
 * render as snake_case to a Turkmen or Russian operator.
 */
function fieldLabel(fieldKey: string, t: TFunction): string {
  return t(`tasks.field_label.${fieldKey}`, {
    defaultValue: t(`shipment_edit_drawer.field.${fieldKey}`, { defaultValue: fieldKey }),
  });
}

/**
 * Render a `condition_value` for reading.
 *
 * Conditions are compared string-cast against `str(getattr(...))` on the Python
 * side, so a boolean gate arrives as `True` / `False` — a Python repr, not a
 * word any operator should have to recognise.
 */
function conditionValue(value: string, t: TFunction): string {
  if (value === 'True') return t('task_rules.value_yes');
  if (value === 'False') return t('task_rules.value_no');
  return value;
}

/**
 * Render a `deadline_rule` string in words.
 *
 * Mirrors the grammar parsed by `parse_deadline_rule` in
 * `backend/apps/export/services/task_rules.py`. An unrecognised rule falls back
 * to the raw string rather than hiding it — the backend logs a warning and
 * treats it as "no deadline", and seeing the odd value is the point of a
 * reference page.
 */
function formatDeadline(rule: string, t: TFunction): string {
  if (!rule || rule === 'none') return '—';

  const hours = /^(\d+)h_after_status$/.exec(rule);
  if (hours) return t('task_rules.deadline_hours', { count: Number(hours[1]) });

  if (rule === 'friday_eow') return t('task_rules.deadline_friday');

  const timeOfDay = /^(\d{2}:\d{2})_(.+)$/.exec(rule);
  if (timeOfDay) {
    const [, time, suffix] = timeOfDay;
    if (suffix === 'same_day') return t('task_rules.deadline_same_day', { time });
    if (suffix === 'next_business_day') {
      return t('task_rules.deadline_next_business_day', { time });
    }
  }
  return rule;
}

/**
 * Task Rules — the read-only catalog behind My Tasks.
 *
 * Answers "when is a task created, who gets it, and what closes it?" from the
 * live `export_task_rule` rows, so the page cannot drift from the engine the
 * way a hand-written list would. Editing rules is not part of this page (yet):
 * changing one leaves existing open tasks on their snapshotted fields until
 * `reconcile_tasks` runs, so writes need that wiring first.
 */
export default function TaskRulesPage() {
  const { t } = useTranslation();
  const { data: rules = [], isLoading, isError } = useTaskRules();
  const [roleFilter, setRoleFilter] = useState<string | null>(null);
  const [showInactive, setShowInactive] = useState(false);

  const roleOptions = useMemo(() => {
    const seen = new Map<string, string>();
    rules.forEach((rule) => seen.set(rule.assignee_role, rule.assignee_role_display));
    return [...seen].map(([value, label]) => ({ value, label }));
  }, [rules]);

  const visibleRules = useMemo(
    () => rules.filter((rule) => (
      (showInactive || rule.is_active)
      && (!roleFilter || rule.assignee_role === roleFilter)
    )),
    [rules, roleFilter, showInactive],
  );

  const columns: ColumnsType<ITaskRule> = [
    {
      title: t('task_rules.col_step'),
      dataIndex: 'step_display',
      key: 'step',
      width: 170,
      render: (_: unknown, rule: ITaskRule) => (
        <Space direction="vertical" size={0}>
          <Text strong>{t(`shipment_status.${rule.step}`, { defaultValue: rule.step_display })}</Text>
          <Text type="secondary" style={{ fontSize: 12 }}>{rule.step}</Text>
        </Space>
      ),
    },
    {
      title: t('task_rules.col_task'),
      dataIndex: 'title_key',
      key: 'title_key',
      render: (_: unknown, rule: ITaskRule) => (
        <Space direction="vertical" size={0}>
          <Text>{t(rule.title_key, { defaultValue: rule.title_key })}</Text>
          {!rule.is_active && <Tag color="default">{t('task_rules.inactive')}</Tag>}
        </Space>
      ),
    },
    {
      title: t('task_rules.col_role'),
      dataIndex: 'assignee_role_display',
      key: 'assignee_role',
      width: 150,
      render: (_: unknown, rule: ITaskRule) => (
        <Tag color="geekblue">{rule.assignee_role_display}</Tag>
      ),
    },
    {
      title: t('task_rules.col_completes'),
      key: 'completion',
      render: (_: unknown, rule: ITaskRule) => (
        <Space direction="vertical" size={2}>
          <Tag color={RULE_COLOR[rule.completion_rule]}>
            {rule.completion_rule === 'manual_done'
              ? t('task_rules.completes_manual')
              : t('task_rules.completes_auto')}
          </Tag>
          {rule.target_fields.length > 0 && (
            <Space size={4} wrap>
              {rule.target_fields.map((field) => (
                <Tag key={field} style={{ margin: 0 }}>
                  {fieldLabel(field, t)}
                  {rule.completion_rule === 'field_equals' && rule.target_value
                    ? ` = ${rule.target_value}`
                    : ''}
                </Tag>
              ))}
            </Space>
          )}
        </Space>
      ),
    },
    {
      title: t('task_rules.col_only_when'),
      key: 'condition',
      width: 170,
      render: (_: unknown, rule: ITaskRule) => (
        rule.condition_field
          ? (
            <Text type="secondary" style={{ fontSize: 12 }}>
              {fieldLabel(rule.condition_field, t)}
              {` = ${conditionValue(rule.condition_value, t)}`}
            </Text>
          )
          : <Text type="secondary">{t('task_rules.condition_always')}</Text>
      ),
    },
    {
      title: t('task_rules.col_deadline'),
      dataIndex: 'deadline_rule',
      key: 'deadline_rule',
      width: 150,
      render: (value: string) => formatDeadline(value, t),
    },
  ];

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <div>
        <Title level={4} style={{ marginBottom: 4 }}>{t('task_rules.title')}</Title>
        <Paragraph type="secondary" style={{ marginBottom: 0 }}>
          {t('task_rules.subtitle')}
        </Paragraph>
      </div>

      <Alert
        type="info"
        showIcon
        message={t('task_rules.how_title')}
        description={(
          <Space direction="vertical" size={4}>
            <Text>{t('task_rules.how_trigger')}</Text>
            <Text>{t('task_rules.how_auto')}</Text>
            <Text>{t('task_rules.how_manual')}</Text>
            <Text>{t('task_rules.how_gating')}</Text>
          </Space>
        )}
      />

      {isError && (
        <Alert type="error" showIcon message={t('task_rules.load_error')} />
      )}

      <Card
        size="small"
        title={t('task_rules.table_title')}
        extra={(
          <Space size={12}>
            <Select
              allowClear
              size="small"
              style={{ minWidth: 190 }}
              placeholder={t('task_rules.filter_role')}
              value={roleFilter}
              onChange={(value) => setRoleFilter(value ?? null)}
              options={roleOptions}
            />
            <Space size={6}>
              <Switch size="small" checked={showInactive} onChange={setShowInactive} />
              <Text type="secondary" style={{ fontSize: 12 }}>
                {t('task_rules.show_inactive')}
              </Text>
            </Space>
          </Space>
        )}
      >
        <Table<ITaskRule>
          rowKey="id"
          size="small"
          loading={isLoading}
          columns={columns}
          dataSource={visibleRules}
          pagination={false}
        />
      </Card>

      <Card size="small" title={t('task_rules.other_kinds_title')}>
        <Paragraph type="secondary">{t('task_rules.other_kinds_intro')}</Paragraph>
        <Table<ICodeDrivenKind>
          rowKey="key"
          size="small"
          pagination={false}
          dataSource={CODE_DRIVEN_KINDS}
          columns={[
            {
              title: t('task_rules.other_kinds_col_task'),
              key: 'name',
              width: 220,
              render: (_: unknown, kind: ICodeDrivenKind) => (
                <Text strong>{t(`task_rules.kind_${kind.key}_name`)}</Text>
              ),
            },
            {
              title: t('task_rules.other_kinds_col_role'),
              key: 'role',
              width: 150,
              render: (_: unknown, kind: ICodeDrivenKind) => (
                <Tag color="geekblue">{t(`roles.${kind.role}`)}</Tag>
              ),
            },
            {
              title: t('task_rules.other_kinds_col_trigger'),
              key: 'trigger',
              render: (_: unknown, kind: ICodeDrivenKind) => (
                <Text>{t(`task_rules.kind_${kind.key}_trigger`)}</Text>
              ),
            },
            {
              title: t('task_rules.col_completes'),
              key: 'completes',
              render: (_: unknown, kind: ICodeDrivenKind) => (
                <Text>{t(`task_rules.kind_${kind.key}_completes`)}</Text>
              ),
            },
          ]}
        />
        <Paragraph type="secondary" style={{ marginTop: 12, marginBottom: 0 }}>
          {t('task_rules.other_kinds_note')}
        </Paragraph>
        <Paragraph type="secondary" style={{ marginBottom: 0 }}>
          {t('task_rules.retired_rule_note')}
        </Paragraph>
      </Card>
    </Space>
  );
}
