"""Task and TaskRule models for the structural-task system.

A TaskRule is a recipe — when a Shipment enters a `step` (status code),
the rule engine generates one Task per matching active TaskRule.

A Task represents work for a specific role on a specific Shipment, with
optional target fields (CSV of Shipment field_keys) and an optional
deadline. Tasks auto-resolve when their target fields are filled (per
completion_rule), or are marked done manually via API.

Architecture notes:
  - target_fields is a CSV CharField, NOT JSONField (CLAUDE.md / MSSQL).
    Read with `[f.strip() for f in value.split(',') if f.strip()]`.
  - TaskRule.condition is split into two scalar columns; only one
    condition per rule. Multi-condition rules are written as multiple
    rules (e.g. one for is_gapy_satys=True, another for False).
  - Auto-resolution lives in `Shipment.save()` (added in B-engine), not
    a Django signal. Bulk operations bypass save() — that's a known
    limit; current write paths all go through serializer.save().
"""
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class TaskKind(models.TextChoices):
    SHIPMENT        = 'shipment',        _('Shipment task')
    WEEKLY_PLAN     = 'weekly_plan',     _('Weekly harvest-plan task')
    LOCAL_SELL_PLAN = 'local_sell_plan', _('Local sell-plan task')


class TaskCompletionRule(models.TextChoices):
    ALL_FIELDS_FILLED = 'all_fields_filled', _('All target fields filled')
    ANY_FIELD_FILLED  = 'any_field_filled',  _('Any target field filled')
    FIELD_EQUALS      = 'field_equals',      _('Target field equals a specific value')
    MANUAL_DONE       = 'manual_done',       _('Marked done manually')


class TaskState(models.TextChoices):
    OPEN        = 'open',        _('Open')
    IN_PROGRESS = 'in_progress', _('In progress')
    BLOCKED     = 'blocked',     _('Blocked')
    DONE        = 'done',        _('Done')
    CANCELLED   = 'cancelled',   _('Cancelled')


class TaskRule(models.Model):
    """A recipe for generating Tasks when a Shipment enters a status."""

    step = models.CharField(
        max_length=32, db_index=True,
        help_text='Shipment status code that triggers this rule',
    )
    title_key = models.CharField(
        max_length=128,
        help_text='i18n key, e.g. tasks.fill_loading_data',
    )
    assignee_role = models.CharField(
        max_length=32,
        help_text='Role that owns the generated Task by default',
    )
    target_fields = models.CharField(
        max_length=512, blank=True, default='',
        help_text='CSV of Shipment field_keys; whitespace-trimmed on read',
    )
    completion_rule = models.CharField(
        max_length=24,
        choices=TaskCompletionRule.choices,
        default=TaskCompletionRule.ALL_FIELDS_FILLED,
    )
    target_value = models.CharField(
        max_length=64, blank=True, default='',
        help_text='For FIELD_EQUALS rules: the value to compare against (string-cast)',
    )
    deadline_rule = models.CharField(
        max_length=64, blank=True, default='',
        help_text='Grammar parsed in services/task_rules.py; e.g. 13:00_same_day',
    )
    condition_field = models.CharField(
        max_length=64, blank=True, default='',
        help_text='Shipment attr name for the gating condition; blank = always match',
    )
    condition_value = models.CharField(
        max_length=64, blank=True, default='',
        help_text='String-cast comparison: str(getattr(shipment, condition_field)) == condition_value',
    )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'export_task_rule'
        indexes = [models.Index(fields=['step', 'is_active'], name='export_task_step_9b30cb_idx')]

    def __str__(self) -> str:
        return f'{self.step}/{self.title_key} → {self.assignee_role}'


class Task(models.Model):
    """A unit of work on a specific Shipment, generated by a TaskRule."""

    shipment = models.ForeignKey(
        'Shipment', on_delete=models.CASCADE, related_name='tasks',
        null=True, blank=True,
        help_text='Parent shipment; null for non-shipment tasks (e.g. weekly_plan)',
    )
    kind = models.CharField(
        max_length=16, choices=TaskKind.choices, default=TaskKind.SHIPMENT,
        db_index=True,
        help_text='Task category. shipment = generated by the status rule engine; '
                  'weekly_plan = per-(manager, block) weekly harvest-plan to-do',
    )
    step = models.CharField(
        max_length=32, db_index=True,
        help_text='Shipment status when the task was generated; '
                  "'weekly_plan' for weekly-plan tasks",
    )
    rule = models.ForeignKey(
        'TaskRule', on_delete=models.PROTECT, related_name='tasks',
        null=True, blank=True,
        help_text='Rule that generated this task; null if ad-hoc',
    )

    title_key = models.CharField(max_length=128)
    assignee_role = models.CharField(max_length=32, db_index=True)
    assignee_user = models.ForeignKey(
        'core.User', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='+',
        help_text='Set when a specific user picks up the task',
    )
    completed_by = models.ForeignKey(
        'core.User',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='completed_tasks',
        help_text='User credited with completing this task; null when no user was in scope.',
    )

    target_fields = models.CharField(max_length=512, blank=True, default='')
    completion_rule = models.CharField(
        max_length=24, choices=TaskCompletionRule.choices,
        default=TaskCompletionRule.ALL_FIELDS_FILLED,
    )
    target_value = models.CharField(
        max_length=64, blank=True, default='',
        help_text='Mirrors TaskRule.target_value at task-create time',
    )

    deadline = models.DateTimeField(
        null=True, blank=True, db_index=True,
        help_text='Computed at task creation from rule.deadline_rule',
    )
    deadline_rule = models.CharField(max_length=64, blank=True, default='')

    # === Non-shipment task context (kind != shipment) ===
    link = models.CharField(
        max_length=255, blank=True, default='',
        help_text='Frontend route the task card navigates to (e.g. weekly_plan grid)',
    )
    scope_year = models.PositiveSmallIntegerField(
        null=True, blank=True,
        help_text='ISO year this task covers (weekly_plan tasks)',
    )
    scope_week = models.PositiveSmallIntegerField(
        null=True, blank=True,
        help_text='ISO week number this task covers (weekly_plan tasks)',
    )
    scope_block = models.ForeignKey(
        'core.GreenhouseBlock', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='+',
        help_text='Block this weekly_plan task covers — one task per (manager, '
                  'block) per ISO week. SET_NULL (not PROTECT) so deleting a '
                  'block is never blocked by an ephemeral reminder task; a '
                  'null-block weekly_plan task is simply skipped by the '
                  'resolver. Always null for shipment tasks.',
    )

    state = models.CharField(
        max_length=16, choices=TaskState.choices,
        default=TaskState.OPEN, db_index=True,
    )
    blocked_reason = models.TextField(blank=True, default='')
    blocked_by = models.ManyToManyField(
        'self', symmetrical=False, blank=True, related_name='blocking',
        help_text='Tasks that must complete before this one can be worked on',
    )

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'export_task'
        indexes = [
            models.Index(fields=['shipment', 'state'], name='export_task_shipmen_e7db76_idx'),
            models.Index(fields=['assignee_role', 'state'], name='export_task_assigne_250b44_idx'),
            models.Index(fields=['state', 'deadline'], name='export_task_state_577027_idx'),
        ]

    def __str__(self) -> str:
        return f'Task<{self.pk}> {self.shipment_id}/{self.title_key} [{self.state}]'

    @property
    def target_field_list(self) -> list[str]:
        """Parse the CSV target_fields into a clean list."""
        if not self.target_fields:
            return []
        return [f.strip() for f in self.target_fields.split(',') if f.strip()]

    @property
    def is_overdue(self) -> bool:
        if not self.deadline:
            return False
        if self.state in (TaskState.DONE, TaskState.CANCELLED):
            return False
        return timezone.now() > self.deadline

    @property
    def duration_seconds(self) -> int | None:
        if not self.started_at:
            return None
        end = self.completed_at or timezone.now()
        return int((end - self.started_at).total_seconds())
