# Generated by Django 5.1.15 on 2026-05-04 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('question', 'Question')], max_length=20)),
                ('title', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=200)),
                ('description', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=4000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('submitted_from_path', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_from_label', models.CharField(blank=True, default='', max_length=120)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=4000)),
                ('mode', models.CharField(choices=[('standard', 'Standard'), ('internal', 'Internal'), ('public', 'Public')], default='standard', max_length=20)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedbackticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackreply')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['author', '-created_at'], name='feedback_fe_author__95434e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['status', '-created_at'], name='feedback_fe_status_4eba76_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reply__isnull', True), ('ticket__isnull', False)), models.Q(('reply__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='attachment_has_exactly_one_parent'),
        ),
    ]
