# Generated by Django 5.1.15 on 2026-04-07 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_gapy_satys_to_firms'),
        ('export', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_column='rejected_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        # MSSQL workaround: AddField with default= fails on constraint drop.
        # Use RunSQL to add the column with default, then drop the default constraint properly.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE [export].[weekly_harvest_plans] ADD [status] nvarchar(20) NOT NULL CONSTRAINT [DF_whp_status] DEFAULT 'draft';",
            ],
            reverse_sql=[
                "ALTER TABLE [export].[weekly_harvest_plans] DROP CONSTRAINT [DF_whp_status];",
                "ALTER TABLE [export].[weekly_harvest_plans] DROP COLUMN [status];",
            ],
            state_operations=[
                migrations.AddField(
                    model_name='weeklyharvestplan',
                    name='status',
                    field=models.CharField(
                        choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                        default='draft',
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('quota_80', 'Quota 80%'), ('quota_90', 'Quota 90%'), ('quota_95', 'Quota 95%'), ('quota_100', 'Quota 100%'), ('overdue', 'Overdue shipment'), ('plan_submitted', 'Plan submitted'), ('plan_approved', 'Plan approved'), ('plan_rejected', 'Plan rejected')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='weeklyharvestplan',
            index=models.Index(fields=['status'], name='ix_harvest_plan_status'),
        ),
    ]
