# Generated by Django 5.1.15 on 2026-04-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0011_move_greenhouse_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotaissuancefirmallocation',
            options={'ordering': ['export_firm__code']},
        ),
    ]
