# Generated by Django 5.1.15 on 2026-04-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_fk_on_delete_protect'),
        ('export', '0013_add_operational_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('kg_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_type', models.CharField(choices=[('tomato', 'Tomato'), ('pepper', 'Pepper')], default='tomato', max_length=20)),
                ('notes', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=500)),
                ('export_firm', models.ForeignKey(db_column='export_firm_id', on_delete=django.db.models.deletion.PROTECT, related_name='quota_usage_records', to='core.exportfirm')),
            ],
            options={
                'db_table': '[export].[quota_usage_records]',
                'ordering': ['usage_date', 'export_firm'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kg_used__gt', 0)), name='chk_usage_kg_gt0')],
            },
        ),
    ]
