# Generated by Django 5.1.15 on 2026-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0015_add_usage_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaissuance',
            name='notes',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quotausagerecord',
            name='notes',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=500),
        ),
    ]
