# Generated by Django 5.1.15 on 2026-04-27 12:02
# Manually edited: any AddField that has a non-null DEFAULT value uses RunSQL
# to work around a django-mssql-backend bug where AddField for columns with
# DEFAULT values generates an unnamed constraint then tries to DROP it by
# column name (instead of the autogenerated constraint name), causing:
#   "'column_name' is not a constraint" error.
# Fields that are fully nullable (null=True, no default) still use AddField.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0020_add_pallet_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # === Fully nullable FKs — safe to use AddField ===
        migrations.AddField(
            model_name='shipmentcomment',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='shipmentcomment',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentcomment',
            name='done_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='completed_comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # field_key is nullable — safe
        migrations.AddField(
            model_name='shipmentcomment',
            name='field_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),

        # === Columns with DEFAULT values — use RunSQL to name the constraint ===

        # is_deleted BIT NOT NULL DEFAULT 0
        migrations.RunSQL(
            sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "ADD [is_deleted] bit NOT NULL "
                "CONSTRAINT [df_sc_is_deleted] DEFAULT 0"
            ),
            reverse_sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "DROP CONSTRAINT [df_sc_is_deleted]; "
                "ALTER TABLE [export].[shipment_comments] DROP COLUMN [is_deleted]"
            ),
            state_operations=[
                migrations.AddField(
                    model_name='shipmentcomment',
                    name='is_deleted',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),

        # is_done BIT NOT NULL DEFAULT 0
        migrations.RunSQL(
            sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "ADD [is_done] bit NOT NULL "
                "CONSTRAINT [df_sc_is_done] DEFAULT 0"
            ),
            reverse_sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "DROP CONSTRAINT [df_sc_is_done]; "
                "ALTER TABLE [export].[shipment_comments] DROP COLUMN [is_done]"
            ),
            state_operations=[
                migrations.AddField(
                    model_name='shipmentcomment',
                    name='is_done',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),

        # role_mentions NVARCHAR(500) NOT NULL DEFAULT ''
        migrations.RunSQL(
            sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "ADD [role_mentions] nvarchar(500) NOT NULL "
                "CONSTRAINT [df_sc_role_mentions] DEFAULT ''"
            ),
            reverse_sql=(
                "ALTER TABLE [export].[shipment_comments] "
                "DROP CONSTRAINT [df_sc_role_mentions]; "
                "ALTER TABLE [export].[shipment_comments] DROP COLUMN [role_mentions]"
            ),
            state_operations=[
                migrations.AddField(
                    model_name='shipmentcomment',
                    name='role_mentions',
                    field=models.CharField(blank=True, default='', max_length=500),
                ),
            ],
        ),

        # === choices change on Notification.kind ===
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(
                choices=[
                    ('quota_80', 'Quota 80%'),
                    ('quota_90', 'Quota 90%'),
                    ('quota_95', 'Quota 95%'),
                    ('quota_100', 'Quota 100%'),
                    ('overdue', 'Overdue shipment'),
                    ('action_required', 'Action required'),
                    ('plan_submitted', 'Plan submitted'),
                    ('plan_approved', 'Plan approved'),
                    ('plan_rejected', 'Plan rejected'),
                    ('mention', 'Mention'),
                    ('task_assigned', 'Task assigned'),
                    ('task_done', 'Task done'),
                ],
                max_length=30,
            ),
        ),

        # === Indexes ===
        migrations.AddIndex(
            model_name='shipmentcomment',
            index=models.Index(
                fields=['shipment', 'field_key'],
                name='ix_comments_shipment_field',
            ),
        ),
        migrations.AddIndex(
            model_name='shipmentcomment',
            index=models.Index(
                fields=['assignee', 'is_done'],
                name='ix_comments_assignee_open',
            ),
        ),
    ]
