# Generated by Django 5.1.15 on 2026-04-29 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0025_shipment_live_status_loading_ended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetRowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(db_index=True, help_text='Matches field_key in DEFAULT_SHEET_ROWS and serializer field names.', max_length=60, unique=True)),
                ('row_number', models.PositiveSmallIntegerField(db_index=True, help_text='Display ordinal from DEFAULT_SHEET_ROWS. Informational only.')),
                ('triggered_role', models.CharField(blank=True, choices=[('export_manager', 'Export Manager'), ('loading_dept_head', 'Loading Dept Head'), ('warehouse_chief', 'Warehouse Chief'), ('weight_master', 'Weight Master'), ('document_team', 'Document Team'), ('transport', 'Transport'), ('sales_rep', 'Sales Rep'), ('finansist', 'Finansist'), ('director', 'Director'), ('accountant', 'Accountant'), ('greenhouse_manager', 'Greenhouse Manager'), ('seller', 'Seller'), ('boss', 'Boss')], default='', help_text='If set, only users with this role may edit this row (AND must have field perm).', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_user', models.ForeignKey(blank=True, help_text='If set, only this specific user may edit this row (AND must have field perm). Inactive user locks the row for everyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_rows_triggered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_sheet_row_setting',
                'constraints': [models.CheckConstraint(condition=models.Q(('triggered_role__gt', ''), ('triggered_user__isnull', False), _negated=True), name='sheet_row_setting_role_xor_user')],
            },
        ),
    ]
