# Generated by Django 5.1.15 on 2026-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0033_sheet_row_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='loading_ended_at',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='vehicle_live_status',
        ),
    ]
