# Generated by Django 5.1.15 on 2026-04-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0034_remove_shipment_loading_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSheetRowPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, help_text='Per-user display position (sparse). Null inherits admin display_order.', null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='User-side row hide. AND-composes with admin is_visible.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='export.sheetrowsetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_row_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_user_sheet_row_pref',
                'constraints': [models.UniqueConstraint(fields=('user', 'row'), name='uq_user_sheet_row_pref')],
            },
        ),
    ]
