# Generated by Django 5.1.15 on 2026-05-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variety', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tabel_no', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, related_name='domestic_sales', to='core.greenhouseblock')),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.PROTECT, related_name='domestic_sales', to='core.domesticbuyer')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_sales_created', to=settings.AUTH_USER_MODEL)),
                ('export_firm', models.ForeignKey(blank=True, db_column='export_firm_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exportfirm')),
            ],
            options={
                'db_table': 'export_domestic_sales',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyHarvestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='ISO week number 1–53.')),
                ('year', models.PositiveSmallIntegerField(help_text='ISO year.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of first formal submission for this week.', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When set, all edits are frozen. Admin can re-open by clearing to NULL.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, to='core.greenhouseblock')),
                ('entered_by', models.ForeignKey(blank=True, db_column='entered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_entered', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season')),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_plans_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_weekly_harvest_plans',
                'ordering': ['year', 'week_number', 'block'],
            },
        ),
        migrations.CreateModel(
            name='HarvestDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Local date (Asia/Ashgabat) this entry covers.')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Mon … 6=Sun. Sunday is allowed for end-of-season harvesting.')),
                ('plan_value', models.DecimalField(blank=True, decimal_places=2, help_text='Planned harvest kg. NULL = not entered.', max_digits=10, null=True)),
                ('plan_submitted_at', models.DateTimeField(blank=True, help_text='UTC timestamp when plan_value was submitted.', null=True)),
                ('plan_state', models.CharField(blank=True, choices=[('on_time', 'on_time'), ('late', 'late'), ('critical_late', 'critical_late')], default='', help_text='Timeliness of plan submission relative to config deadlines.', max_length=16)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast harvest kg. NULL = not entered.', max_digits=10, null=True)),
                ('forecast_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('forecast_window', models.CharField(blank=True, choices=[('primary', 'primary'), ('fallback', 'fallback'), ('same_day_red_flag', 'same_day_red_flag')], default='', help_text='Which time window the forecast was submitted in.', max_length=24)),
                ('forecast_revision_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times the forecast value has been revised (first entry = 0).')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual harvest kg. NULL = not yet recorded.', max_digits=10, null=True)),
                ('actual_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('actual_source', models.CharField(blank=True, choices=[('manual', 'manual'), ('pallet_rollup_pending', 'pallet_rollup_pending')], default='', help_text='How actual_value was set.', max_length=24)),
                ('last_override_at', models.DateTimeField(blank=True, null=True)),
                ('last_override_reason', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', help_text='Most-recent admin override reason (Cyrillic/Latin mixed).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, to='core.greenhouseblock')),
                ('forecast_submitted_by', models.ForeignKey(blank=True, db_column='forecast_submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_override_by', models.ForeignKey(blank=True, db_column='last_override_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_submitted_by', models.ForeignKey(blank=True, db_column='plan_submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season')),
                ('weekly_plan', models.ForeignKey(db_column='weekly_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='greenhouse.weeklyharvestplan')),
            ],
            options={
                'db_table': 'export_harvest_day_entries',
                'ordering': ['entry_date', 'block__code'],
            },
        ),
        migrations.CreateModel(
            name='BlockManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='core.greenhouseblock')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='block_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_block_manager_assignments',
                'ordering': ['user', 'block__code'],
                'constraints': [models.UniqueConstraint(fields=('user', 'block'), name='uq_block_manager_assignment')],
            },
        ),
        migrations.CreateModel(
            name='HarvestDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_kind', models.CharField(choices=[('t1_forecast_nudge', 'T1 Forecast Nudge'), ('t2_forecast_handoff', 'T2 Forecast Handoff'), ('t3_forecast_escalation', 'T3 Forecast Escalation'), ('p1_plan_reminder', 'P1 Plan Reminder'), ('p2_plan_late', 'P2 Plan Late'), ('p3_plan_critical_late', 'P3 Plan Critical-Late')], max_length=30)),
                ('scope_date', models.DateField(help_text='The date this trigger is scoped to (tomorrow for forecasts, plan-week-start for plan triggers).')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(db_column='target_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_harvest_dispatch_log',
                'ordering': ['-fired_at'],
                'constraints': [models.UniqueConstraint(fields=('trigger_kind', 'target_user', 'scope_date'), name='uq_harvest_dispatch_log')],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyharvestplan',
            constraint=models.UniqueConstraint(fields=('season', 'block', 'week_number', 'year'), name='uq_weekly_plan'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['block', 'entry_date'], name='ix_hde_block_date'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['entry_date'], name='ix_hde_date'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['season', 'entry_date'], name='ix_hde_season_date'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.UniqueConstraint(fields=('weekly_plan', 'entry_date'), name='uq_hde_plan_date'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='chk_hde_weekday'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('plan_value__isnull', True), ('plan_value__gte', 0), _connector='OR'), name='chk_hde_plan_gte0'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('forecast_value__isnull', True), ('forecast_value__gte', 0), _connector='OR'), name='chk_hde_fc_gte0'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('actual_value__isnull', True), ('actual_value__gte', 0), _connector='OR'), name='chk_hde_act_gte0'),
        ),
    ]
