# Generated by Django 5.1.15 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestdayentry',
            name='actual_source',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('pallet_rollup_pending', 'pallet_rollup_pending'), ('admin_override', 'admin_override')], default='', help_text='How actual_value was set. admin_override marks a value the daily shipment-rollup job must leave alone.', max_length=24),
        ),
    ]
