# Generated by Django 5.1.15 on 2026-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticsale',
            name='notes',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='domesticsale',
            name='variety',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True),
        ),
    ]
