# Generated by Django 5.1.15 on 2026-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_alter_harvestdayentry_actual_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestdayentry',
            name='actual_source',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('pallet_rollup_pending', 'pallet_rollup_pending'), ('admin_override', 'admin_override'), ('shipment_rollup', 'shipment_rollup')], default='', help_text='How actual_value was set. shipment_rollup is the daily computed source; admin_override marks a value the rollup must leave alone.', max_length=24),
        ),
    ]
