# Generated by Django 5.1.15 on 2026-05-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_alter_harvestdayentry_actual_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='submitted_by',
        ),
    ]
