# Generated by Django 5.1.15 on 2026-04-30 07:03
# Manually edited: inserted backfill RunPython between new-model setup and wide-column drops.
#
# Migration sequence:
#   1. CreateModel HarvestDayEntry + HarvestDispatchLog (shell only — no FKs yet)
#   2. AddField FK columns on HarvestDayEntry (weekly_plan, season, block, *_submitted_by, etc.)
#   3. RunPython backfill_day_entries — reads wide columns (still exist), writes HarvestDayEntry rows
#   4. RemoveConstraint, RemoveIndex, RemoveField wide columns
#   5. AddField locked_at + AlterField + AddIndex + AddConstraint
#
# Data-migration notes:
#   - actual_weekly_total_kg rows: where WeeklyHarvestPlan had ONLY an aggregate weekly actual
#     (no per-day breakdown), those 6 daily HarvestDayEntry rows get actual_value=NULL.
#     This is acceptable — the aggregate was an import-only fallback and has no per-day semantics.
#   - plan_state is set to 'on_time' for all historical rows (best-effort; submission timestamps
#     pre-date the config-driven deadline system).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_day_entries(apps, schema_editor):
    """Explode WeeklyHarvestPlan wide columns into HarvestDayEntry rows (Mon-Sat).

    Zero/null distinction:
    - plan_value = 0 AND submitted_at IS NULL → leave plan_value = NULL (never entered).
    - plan_value > 0 → carry value forward; set plan_state = 'on_time' (historical best-effort).
    - actual_weekly_total_kg: not exploded into per-day rows — the aggregate had no per-day data.
    """
    from datetime import date

    WeeklyHarvestPlan = apps.get_model('greenhouse', 'WeeklyHarvestPlan')
    HarvestDayEntry = apps.get_model('greenhouse', 'HarvestDayEntry')

    DAYS = ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday')
    entries = []

    for plan in WeeklyHarvestPlan.objects.all().iterator(chunk_size=200):
        try:
            # week_number is ISO week; day 1 = Monday
            week_start = date.fromisocalendar(plan.year, plan.week_number, 1)
        except ValueError:
            # Malformed historical row (invalid week/year combo) — skip
            continue

        for idx, day in enumerate(DAYS):
            plan_kg = getattr(plan, f'{day}_plan_kg', None)
            actual_kg = getattr(plan, f'{day}_actual_kg', None)
            # idx 0 = Monday (ISO day 1), idx 5 = Saturday (ISO day 6)
            entry_date = date.fromisocalendar(plan.year, plan.week_number, idx + 1)

            # "Never entered" semantics: plan_kg=0 AND submitted_at IS NULL → plan_value=NULL
            if plan_kg is not None and (plan_kg > 0 or plan.submitted_at is not None):
                plan_value = plan_kg
                plan_submitted_at = plan.submitted_at
                plan_submitted_by_id = plan.submitted_by_id
                plan_state = 'on_time'  # best-effort historical assumption
            else:
                plan_value = None
                plan_submitted_at = None
                plan_submitted_by_id = None
                plan_state = ''

            actual_value = actual_kg
            actual_finalized_at = plan.updated_at if actual_kg is not None else None
            actual_source = 'manual' if actual_kg is not None else ''

            entries.append(HarvestDayEntry(
                weekly_plan_id=plan.id,
                season_id=plan.season_id,
                block_id=plan.block_id,
                entry_date=entry_date,
                weekday=idx,
                plan_value=plan_value,
                plan_submitted_at=plan_submitted_at,
                plan_submitted_by_id=plan_submitted_by_id,
                plan_state=plan_state,
                actual_value=actual_value,
                actual_finalized_at=actual_finalized_at,
                actual_source=actual_source,
            ))

    # Per-row save is used here instead of bulk_create: the mssql-django
    # backend has shown intermittent "nvarchar to numeric overflow" errors
    # under bulk_create within a migration's atomic block. The data volume
    # is small (~2k rows) so per-row saves are acceptable.
    for e in entries:
        e.save()


def reverse_backfill(apps, schema_editor):
    """Remove all HarvestDayEntry rows (rollback: wide columns will be restored)."""
    HarvestDayEntry = apps.get_model('greenhouse', 'HarvestDayEntry')
    HarvestDayEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_greenhouseconfig_operatingdayexception'),
        ('greenhouse', '0003_delete_subblock_harvest_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Step 1: Create new model tables (without FK columns yet) ---
        migrations.CreateModel(
            name='HarvestDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Local date (Asia/Ashgabat) this entry covers.')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Mon … 6=Sun. Sunday is allowed for end-of-season harvesting.')),
                ('plan_value', models.DecimalField(blank=True, decimal_places=2, help_text='Planned harvest kg. NULL = not entered.', max_digits=10, null=True)),
                ('plan_submitted_at', models.DateTimeField(blank=True, help_text='UTC timestamp when plan_value was submitted.', null=True)),
                ('plan_state', models.CharField(blank=True, choices=[('on_time', 'on_time'), ('late', 'late'), ('critical_late', 'critical_late')], default='', help_text='Timeliness of plan submission relative to config deadlines.', max_length=16)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast harvest kg. NULL = not entered.', max_digits=10, null=True)),
                ('forecast_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('forecast_window', models.CharField(blank=True, choices=[('primary', 'primary'), ('fallback', 'fallback'), ('same_day_red_flag', 'same_day_red_flag')], default='', help_text='Which time window the forecast was submitted in.', max_length=24)),
                ('forecast_revision_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times the forecast value has been revised (first entry = 0).')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual harvest kg. NULL = not yet recorded.', max_digits=10, null=True)),
                ('actual_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('actual_source', models.CharField(blank=True, choices=[('manual', 'manual'), ('pallet_rollup_pending', 'pallet_rollup_pending')], default='', help_text='How actual_value was set.', max_length=24)),
                ('last_override_at', models.DateTimeField(blank=True, null=True)),
                ('last_override_reason', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', help_text='Most-recent admin override reason (Cyrillic/Latin mixed).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '[export].[harvest_day_entries]',
                'ordering': ['entry_date', 'block__code'],
            },
        ),
        migrations.CreateModel(
            name='HarvestDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_kind', models.CharField(choices=[('t1_forecast_nudge', 'T1 Forecast Nudge'), ('t2_forecast_handoff', 'T2 Forecast Handoff'), ('t3_forecast_escalation', 'T3 Forecast Escalation'), ('p1_plan_reminder', 'P1 Plan Reminder'), ('p2_plan_late', 'P2 Plan Late'), ('p3_plan_critical_late', 'P3 Plan Critical-Late')], max_length=30)),
                ('scope_date', models.DateField(help_text='The date this trigger is scoped to (tomorrow for forecasts, plan-week-start for plan triggers).')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '[export].[harvest_dispatch_log]',
                'ordering': ['-fired_at'],
            },
        ),

        # --- Step 2: Add FK columns on HarvestDayEntry (fully usable for backfill) ---
        migrations.AddField(
            model_name='harvestdayentry',
            name='block',
            field=models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, to='core.greenhouseblock'),
        ),
        migrations.AddField(
            model_name='harvestdayentry',
            name='forecast_submitted_by',
            field=models.ForeignKey(blank=True, db_column='forecast_submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestdayentry',
            name='last_override_by',
            field=models.ForeignKey(blank=True, db_column='last_override_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestdayentry',
            name='plan_submitted_by',
            field=models.ForeignKey(blank=True, db_column='plan_submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestdayentry',
            name='season',
            field=models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.PROTECT, to='core.season'),
        ),
        migrations.AddField(
            model_name='harvestdayentry',
            name='weekly_plan',
            field=models.ForeignKey(db_column='weekly_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='greenhouse.weeklyharvestplan'),
        ),
        migrations.AddField(
            model_name='harvestdispatchlog',
            name='target_user',
            field=models.ForeignKey(db_column='target_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # --- Step 3: Backfill HarvestDayEntry from wide columns (BEFORE dropping them) ---
        migrations.RunPython(backfill_day_entries, reverse_backfill),

        # --- Step 4: Drop wide columns and approval workflow fields ---
        migrations.RemoveConstraint(
            model_name='weeklyharvestplan',
            name='chk_harvest_plan_kg_gte0',
        ),
        migrations.RemoveIndex(
            model_name='weeklyharvestplan',
            name='ix_harvest_plan_status',
        ),
        # mssql-django does not auto-drop FK constraint + FK index when removing
        # an FK column. Drop them explicitly before RemoveField.
        migrations.RunSQL(
            sql=[
                # FK constraint + FK index for approved_by/rejected_by FKs.
                "ALTER TABLE [export].[weekly_harvest_plans] DROP CONSTRAINT [export_weekly_harvest_plans_approved_by_a428fdda_fk_sys_users_id]",
                "DROP INDEX [export_weekly_harvest_plans_approved_by_a428fdda] ON [export].[weekly_harvest_plans]",
                "ALTER TABLE [export].[weekly_harvest_plans] DROP CONSTRAINT [export_weekly_harvest_plans_rejected_by_59922cfd_fk_sys_users_id]",
                "DROP INDEX [export_weekly_harvest_plans_rejected_by_59922cfd] ON [export].[weekly_harvest_plans]",
                # Default constraint on status (was set when the column had default='draft').
                "ALTER TABLE [export].[weekly_harvest_plans] DROP CONSTRAINT [DF_whp_status]",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='actual_weekly_total_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='friday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='friday_plan_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='monday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='monday_plan_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='rejection_note',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='saturday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='saturday_plan_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='thursday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='thursday_plan_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='tuesday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='tuesday_plan_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='wednesday_actual_kg',
        ),
        migrations.RemoveField(
            model_name='weeklyharvestplan',
            name='wednesday_plan_kg',
        ),

        # --- Step 5: Add locked_at + alter fields + indexes + constraints ---
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When set, all edits are frozen. Admin can re-open by clearing to NULL.', null=True),
        ),
        migrations.AlterField(
            model_name='weeklyharvestplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp of first formal submission for this week.', null=True),
        ),
        migrations.AlterField(
            model_name='weeklyharvestplan',
            name='week_number',
            field=models.PositiveSmallIntegerField(help_text='ISO week number 1–53.'),
        ),
        migrations.AlterField(
            model_name='weeklyharvestplan',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='ISO year.'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['block', 'entry_date'], name='ix_hde_block_date'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['entry_date'], name='ix_hde_date'),
        ),
        migrations.AddIndex(
            model_name='harvestdayentry',
            index=models.Index(fields=['season', 'entry_date'], name='ix_hde_season_date'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.UniqueConstraint(fields=('weekly_plan', 'entry_date'), name='uq_hde_plan_date'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='chk_hde_weekday'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('plan_value__isnull', True), ('plan_value__gte', 0), _connector='OR'), name='chk_hde_plan_gte0'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('forecast_value__isnull', True), ('forecast_value__gte', 0), _connector='OR'), name='chk_hde_fc_gte0'),
        ),
        migrations.AddConstraint(
            model_name='harvestdayentry',
            constraint=models.CheckConstraint(condition=models.Q(('actual_value__isnull', True), ('actual_value__gte', 0), _connector='OR'), name='chk_hde_act_gte0'),
        ),
        migrations.AddConstraint(
            model_name='harvestdispatchlog',
            constraint=models.UniqueConstraint(fields=('trigger_kind', 'target_user', 'scope_date'), name='uq_harvest_dispatch_log'),
        ),
    ]
