# Generated by Django 5.1.15 on 2026-06-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_drop_weeklyharvestplan_submitted_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='late_edit_granted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the extension was granted.', null=True),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='late_edit_granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who granted the late-edit extension.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='late_edit_granted_reason',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', help_text='Reason for granting late-edit access (Cyrillic/Latin mixed).', max_length=500),
        ),
        migrations.AddField(
            model_name='weeklyharvestplan',
            name='late_edit_granted_until',
            field=models.DateTimeField(blank=True, help_text='If set and in the future, greenhouse_manager may still edit plan values.', null=True),
        ),
    ]
