# Generated by Django 5.1.15 on 2026-09-18 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_greenhouseconfig_plan_change_max_pct"),
        ("greenhouse", "0006_harvestdayentry_daily_board"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Week-start baseline at request time. NULL = empty cell (no % bound).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approved plan_value at request time.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "requested_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(requested - baseline) / baseline * 100. NULL when no bound applies.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("superseded", "superseded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        default="",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "export_plan_change_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddField(
            model_name="harvestdayentry",
            name="plan_baseline_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Week-start plan, frozen on the first in-week change request (ADR-024). The ±plan_change_max_pct bound is measured against it.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="harvestdayentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plan_baseline_value__isnull", True),
                    ("plan_baseline_value__gte", 0),
                    _connector="OR",
                ),
                name="chk_hde_baseline_gte0",
            ),
        ),
        migrations.AddField(
            model_name="planchangerequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approver/rejecter, or the user whose action superseded the request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planchangerequest",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="greenhouse.harvestdayentry",
            ),
        ),
        migrations.AddField(
            model_name="planchangerequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="planchangerequest",
            index=models.Index(
                fields=["status", "requested_at"], name="ix_pcr_status_requested"
            ),
        ),
        migrations.AddConstraint(
            model_name="planchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("entry",),
                name="uq_pcr_one_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="planchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_value__gte", 0)),
                name="chk_pcr_requested_gte0",
            ),
        ),
    ]
