# Generated by Django 5.1.15 on 2026-10-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0076_seed_agent_market_perms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bazaar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=60
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.city",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bazaars",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "db_table": "market_bazaars",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_members",
                        to="core.customer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bazaar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="market.bazaar",
                    ),
                ),
            ],
            options={
                "db_table": "market_agent_members",
            },
        ),
        migrations.AddConstraint(
            model_name="bazaar",
            constraint=models.UniqueConstraint(
                fields=("customer", "name"), name="market_bazaar_customer_name_uniq"
            ),
        ),
    ]
