# Generated by Django 5.1.15 on 2026-10-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_seed_agent_market_perms"),
        ("export", "0099_agent_role_choices"),
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=60
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_buyers",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "db_table": "market_buyers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boxes_received", models.PositiveIntegerField()),
                ("boxes_per_pallet", models.PositiveIntegerField()),
                ("tare_g", models.PositiveIntegerField(default=450)),
                (
                    "default_price_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_lot",
                        to="export.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "market_lots",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="LotExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, db_collation="Cyrillic_General_CI_AS", max_length=40
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="export.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="market.lot",
                    ),
                ),
            ],
            options={
                "db_table": "market_lot_expenses",
                "ordering": ["-recorded_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("box", "Box"),
                            ("pallet", "Pallet"),
                            ("truck", "Whole truck"),
                        ],
                        max_length=10,
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                ("boxes", models.PositiveIntegerField()),
                ("gross_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tare_g", models.PositiveIntegerField()),
                ("net_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("calc_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_on_spot", models.BooleanField(default=True)),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="market.buyer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="market.lot",
                    ),
                ),
            ],
            options={
                "db_table": "market_sales",
                "ordering": ["-sold_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Spoilage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boxes", models.PositiveIntegerField(default=0)),
                (
                    "gross_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tare_g", models.PositiveIntegerField()),
                (
                    "net_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spoilage",
                        to="market.lot",
                    ),
                ),
            ],
            options={
                "db_table": "market_spoilage",
                "ordering": ["-recorded_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="buyer",
            constraint=models.UniqueConstraint(
                fields=("customer", "name"), name="market_buyer_customer_name_uniq"
            ),
        ),
    ]
