# Generated by Django 5.1.15 on 2026-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_market_expense_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="receipt_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
