# Generated by Django 5.1.15 on 2026-04-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_gapy_satys_to_firms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_destinations', to='core.country')),
            ],
            options={
                'db_table': '[core].[truck_destinations]',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
