# Generated by Django 5.1.15 on 2026-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_seller_role_and_permission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='import_firms',
            field=models.ManyToManyField(blank=True, db_table='[core].[customer_import_firms]', related_name='customers', to='core.importfirm'),
        ),
    ]
