# Generated by Django 5.1.15 on 2026-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_import_firms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('label_tk', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('label_en', models.CharField(blank=True, max_length=100, null=True)),
                ('label_ru', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '[core].[shipment_option_types]',
                'ordering': ['category', 'sort_order'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
