# Generated by Django 5.1.15 on 2026-07-31 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "transport_drivers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TraccarDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traccar_id", models.IntegerField(unique=True)),
                ("imei", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=100
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(default="unknown", max_length=10)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transport_traccar_devices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=20, unique=True)),
                (
                    "fleet_no",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("trailer", "Trailer"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "transport_trucks",
                "ordering": ["fleet_no", "plate"],
            },
        ),
        migrations.CreateModel(
            name="DevicePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "course",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("ignition", models.BooleanField(blank=True, null=True)),
                ("fix_time", models.DateTimeField(blank=True, null=True)),
                ("valid", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="transport.traccardevice",
                    ),
                ),
            ],
            options={
                "db_table": "transport_device_positions",
            },
        ),
        migrations.AddField(
            model_name="traccardevice",
            name="truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="transport.truck",
            ),
        ),
    ]
