# Generated by Django 5.1.15 on 2026-08-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_shipmentdevicelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=50, unique=True)),
                ("owner_type", models.CharField(blank=True, default="", max_length=20)),
                ("status", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transport_trailers",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="TruckHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=50, unique=True)),
                ("owner_type", models.CharField(blank=True, default="", max_length=20)),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        default="",
                        max_length=200,
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=20)),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "traccar_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="truck_heads",
                        to="transport.traccardevice",
                    ),
                ),
            ],
            options={
                "db_table": "transport_truck_heads",
                "ordering": ["plate_number"],
            },
        ),
    ]
