# Generated by Django 5.1.15 on 2026-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_trailer_truckhead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truckhead",
            name="capacity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
