# Generated by Django 5.1.15 on 2026-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0004_alter_truckhead_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driver_logo_code",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="driver",
            name="logo_ref",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
