# Generated by Django 5.1.15 on 2026-09-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0007_truckheaddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraccarGeofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traccar_id", models.IntegerField(unique=True)),
                (
                    "name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=128
                    ),
                ),
            ],
            options={
                "db_table": "transport_traccar_geofences",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="deviceposition",
            name="geofence_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deviceposition",
            name="current_geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="positions",
                to="transport.traccargeofence",
            ),
        ),
    ]
