# Generated by Django 5.1.15 on 2026-09-29 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export", "0081_block_source_batch_key"),
        ("transport", "0008_traccar_geofence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalTripSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cursor", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_auth_alert_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transport_external_trip_sync_state",
            },
        ),
        migrations.CreateModel(
            name="ExternalTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integration_trip_id", models.UUIDField(unique=True)),
                ("trip_number", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(max_length=30)),
                ("planned_departure", models.DateField()),
                ("changed_at", models.DateTimeField()),
                (
                    "destination_country_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("tractor_plate", models.CharField(max_length=50)),
                (
                    "tractor_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tractor_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tractor_company",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("tractor_source", models.CharField(max_length=20)),
                ("trailer_plate", models.CharField(max_length=50)),
                (
                    "trailer_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trailer_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trailer_company",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("trailer_source", models.CharField(max_length=20)),
                (
                    "driver_full_name",
                    models.CharField(
                        db_collation="Cyrillic_General_CI_AS", max_length=200
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "driver_passport_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("driver_passport_expiry", models.DateField(blank=True, null=True)),
                (
                    "driver_visas",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        default="",
                        max_length=500,
                    ),
                ),
                ("driver_source", models.CharField(max_length=20)),
                (
                    "conflict_note",
                    models.TextField(
                        blank=True, db_collation="Cyrillic_General_CI_AS", null=True
                    ),
                ),
                (
                    "last_push_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_push_error", models.TextField(blank=True, null=True)),
                (
                    "last_pushed_export_code",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_trip",
                        to="export.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "transport_external_trips",
                "ordering": ["planned_departure", "id"],
            },
        ),
    ]
