# Generated by Django 5.1.15 on 2026-09-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0009_external_trips"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltrip",
            name="conflict_from",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="conflict_kind",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="conflict_to",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_loading",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=500,
                null=True,
            ),
        ),
    ]
