# Generated by Django 5.1.15 on 2026-10-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0010_trip_conflict_fields_and_loading_marker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_arrived",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_cargo",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_customs",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_departed",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_destination_city",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="last_pushed_loaded",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externaltrip",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                db_collation="Cyrillic_General_CI_AS",
                max_length=512,
                null=True,
            ),
        ),
    ]
