# Generated by Django 5.1.15 on 2026-06-03 06:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_add_sort_order_to_reference_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100, unique=True)),
                ('contract_type', models.CharField(default='EXPORT', max_length=20)),
                ('incoterm', models.CharField(blank=True, default='', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('planned_trucks', models.IntegerField(blank=True, null=True)),
                ('planned_quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exported_trucks', models.IntegerField(default=0)),
                ('exported_quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('exported_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_received_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('remaining_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('last_invoice_number', models.IntegerField(blank=True, null=True)),
                ('sent_to_unk', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.customer')),
                ('export_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.exportfirm')),
                ('import_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.importfirm')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.season')),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-created_at'],
            },
        ),
    ]
