# Generated by Django 5.1.15 on 2026-06-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('core', '0016_add_sort_order_to_reference_tables'),
        ('export', '0026_add_transport_docs_given_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('serial_truck_number', models.IntegerField(blank=True, null=True)),
                ('incoterm', models.CharField(blank=True, default='', max_length=10)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('passport_sdelka', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=100)),
                ('scan_uploaded', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('void', 'Void')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contracts.contract')),
                ('export_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.exportfirm')),
                ('import_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.importfirm')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='export.shipment')),
            ],
            options={
                'db_table': 'contracts_invoice',
                'ordering': ['contract_id', 'invoice_number'],
                'unique_together': {('contract', 'invoice_number')},
            },
        ),
    ]
