# Generated by Django 5.1.15 on 2026-06-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_invoice_to_contract_sale'),
        ('core', '0023_exportfirm_name_short'),
        ('export', '0047_relabel_rejected_weight_to_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='export_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.exportfirm'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='import_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.importfirm'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='export.shipment'),
        ),
    ]
