# Generated by Django 5.1.15 on 2026-06-25 04:44

import re

from django.conf import settings
from django.db import migrations, models

# Standard contract number: `{seq}/{YY}-{SELLER}-EXP, ...`. Group 1 = seq, 2 = YY.
# Inlined (not imported from services) so the migration is self-contained.
_CONTRACT_NO_RE = re.compile(r'^\s*(\d+)/(\d{2})-([A-Za-z]+)-EXP')


def backfill_seq_year(apps, schema_editor):
    """Populate seq / contract_year from existing standard contract numbers.

    Non-standard numbers (-P pepper, TAT-, legacy) are left NULL and excluded
    from the filtered unique constraint added next.
    """
    Contract = apps.get_model('contracts', 'Contract')
    to_update = []
    for contract in Contract.objects.all().only('id', 'contract_number', 'seq', 'contract_year'):
        match = _CONTRACT_NO_RE.match(str(contract.contract_number or ''))
        if not match:
            continue
        contract.seq = int(match.group(1))
        contract.contract_year = 2000 + int(match.group(2))
        to_update.append(contract)
    if to_update:
        Contract.objects.bulk_update(to_update, ['seq', 'contract_year'], batch_size=500)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_rename_sale_permission_codes'),
        ('core', '0023_exportfirm_name_short'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_seq_year, noop),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_year__isnull', False), ('seq__isnull', False)), fields=('export_firm', 'contract_year', 'seq'), name='uq_contract_firm_year_seq'),
        ),
    ]
