# Generated by Django 5.1.15 on 2026-06-25 06:58

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    """Rename legacy 'EXPORT' type → 'FRAMEWORK' and lift passport-sdelka to the
    contract (copying a non-empty value from any of its sales)."""
    Contract = apps.get_model('contracts', 'Contract')
    ContractSale = apps.get_model('contracts', 'ContractSale')

    Contract.objects.filter(contract_type='EXPORT').update(contract_type='FRAMEWORK')

    to_update = []
    for contract in Contract.objects.all().only('id', 'passport_sdelka'):
        if contract.passport_sdelka:
            continue
        sale = (
            ContractSale.objects.filter(contract_id=contract.id)
            .exclude(passport_sdelka='')
            .only('passport_sdelka')
            .first()
        )
        if sale and sale.passport_sdelka:
            contract.passport_sdelka = sale.passport_sdelka
            to_update.append(contract)
    if to_update:
        Contract.objects.bulk_update(to_update, ['passport_sdelka'], batch_size=500)


def reverse_data(apps, schema_editor):
    Contract = apps.get_model('contracts', 'Contract')
    Contract.objects.filter(contract_type='FRAMEWORK').update(contract_type='EXPORT')


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_contract_year_contract_seq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='passport_sdelka',
            field=models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('FRAMEWORK', 'Framework'), ('ONE_TIME', 'One-time')], default='FRAMEWORK', max_length=20),
        ),
        migrations.RunPython(migrate_data, reverse_data),
    ]
