# Generated by Django 5.1.15 on 2026-06-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_passport_sdelka_and_more'),
        ('core', '0023_exportfirm_name_short'),
        ('export', '0047_relabel_rejected_weight_to_load'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractsale',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='contractsale',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('contract', 'invoice_number'), name='uq_sale_contract_invoice'),
        ),
        migrations.AddConstraint(
            model_name='contractsale',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment__isnull', False)), fields=('shipment', 'export_firm'), name='uq_sale_shipment_firm'),
        ),
    ]
