# Generated by Django 5.1.15 on 2026-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_alter_contractsale_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractsale",
            name="box_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractsale",
            name="gross_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractsale",
            name="pallet_count",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractsale",
            name="pallet_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
