# Generated by Django 5.1.15 on 2026-07-28 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_contractsale_box_count_contractsale_gross_kg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSaleLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveSmallIntegerField()),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        default="",
                        max_length=200,
                    ),
                ),
                ("hs_code", models.CharField(blank=True, default="", max_length=20)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gross_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("box_count", models.IntegerField(blank=True, null=True)),
                ("price_per_kg", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "total_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="contracts.contractsale",
                    ),
                ),
            ],
            options={
                "db_table": "contracts_contract_sale_line_item",
                "ordering": ["sale_id", "line_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sale", "line_number"), name="uq_sale_line_number"
                    )
                ],
            },
        ),
    ]
