# Generated by Django 5.1.15 on 2026-08-13 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_contractsalelineitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLayoutSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_key",
                    models.CharField(
                        help_text="Registry document key (e.g. invoice_ru). The four CMR keys are rejected: their geometry registers onto a pre-printed form.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "font_scale_pct",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Scales every run's font size. 80-120; 100 = the template unchanged.",
                    ),
                ),
                (
                    "line_spacing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Line spacing multiple, 1.0-2.0. Null = leave the template alone.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("margin_top_delta_mm", models.SmallIntegerField(default=0)),
                ("margin_bottom_delta_mm", models.SmallIntegerField(default=0)),
                ("margin_left_delta_mm", models.SmallIntegerField(default=0)),
                ("margin_right_delta_mm", models.SmallIntegerField(default=0)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Incremented on every save(). Used for optimistic locking in PATCH.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contracts_document_layout_setting",
                "ordering": ["document_key"],
            },
        ),
    ]
