# Generated by Django 5.1.15 on 2026-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_documentlayoutsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True
            ),
        ),
    ]
