# Generated by Django 5.1.15 on 2026-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_contract_contract_date_contract_price_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="agreement_downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
