# Generated by Django 5.1.15 on 2026-10-05 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_seed_invoice_number_bases"),
        ("core", "0072_exportfirm_letterhead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractsale",
            name="ct1_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractsale",
            name="customs_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractsale",
            name="fito_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LetterNumberBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("ct1", "ct1"),
                            ("fito", "fito"),
                            ("customs", "customs"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("last_number", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="letter_number_bases",
                        to="core.exportfirm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contracts_letter_number_base",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("export_firm", "letter_type", "year"),
                        name="uq_letter_base_firm_type_year",
                    )
                ],
            },
        ),
    ]
