# Generated by Django 5.1.15 on 2026-10-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_letter_numbers"),
        ("core", "0074_seed_pepper_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="core.producttype",
            ),
        ),
    ]
