"""Tests for per-seller / per-year contract numbering (ADR-023, Slice 1).

Covers the `contract_number` service (parse / next-seq / build / allocate), the
filtered unique constraint (export_firm, contract_year, seq), and the
auto-generation wired into ContractCreateSerializer.
"""
import datetime

from django.db import IntegrityError, transaction
from django.test import TestCase

from apps.core.models import ExportFirm, ImportFirm
from apps.contracts.models import Contract
from apps.contracts.serializers import ContractCreateSerializer
from apps.contracts.services.contract_number import (
    build_contract_number,
    next_contract_no,
    next_contract_seq,
    parse_contract_number,
)


def _efirm(code: str) -> ExportFirm:
    return ExportFirm.objects.create(code=code, name_tk=f'Export {code}')


def _ifirm(code: str) -> ImportFirm:
    return ImportFirm.objects.create(code=code, name_company=f'Import {code}')


def _contract(num, firm, imp, *, seq=None, year=None) -> Contract:
    return Contract.objects.create(
        contract_number=num,
        export_firm=firm,
        import_firm=imp,
        seq=seq,
        contract_year=year,
        start_date='2025-09-22',
    )


class ParseContractNumberTest(TestCase):
    def test_standard_numbers_parse(self) -> None:
        self.assertEqual(parse_contract_number('177/25-YGT-EXP, 22.09.2025'), (177, 2025))
        self.assertEqual(parse_contract_number('1/26-AB-EXP, 16.02.2026'), (1, 2026))
        self.assertEqual(parse_contract_number('  42/26-DM-EXP'), (42, 2026))

    def test_non_standard_returns_none(self) -> None:
        for raw in ['177-AM-P', 'TAT-AM/01/2025', '2026', '5, 30.09.2025', '', None]:
            self.assertIsNone(parse_contract_number(raw), raw)


class BuildContractNumberTest(TestCase):
    def test_format(self) -> None:
        self.assertEqual(
            build_contract_number('YGT', 6, datetime.date(2026, 1, 6)),
            '6/26-YGT-EXP, 06.01.2026',
        )


class NextContractSeqTest(TestCase):
    def test_counter_is_per_seller_and_per_year(self) -> None:
        ygt, hms = _efirm('YGT'), _efirm('HMS')
        buyer = _ifirm('B1')
        _contract('177/25-YGT-EXP', ygt, buyer, seq=177, year=2025)
        _contract('151/25-HMS-EXP', hms, buyer, seq=151, year=2025)
        # YGT 2025 continues from 177; HMS independent; 2026 resets per seller
        self.assertEqual(next_contract_seq(ygt.id, 2025), 178)
        self.assertEqual(next_contract_seq(hms.id, 2025), 152)
        self.assertEqual(next_contract_seq(ygt.id, 2026), 1)

    def test_counter_continues_across_buyers(self) -> None:
        ygt = _efirm('YGT')
        b1, b2 = _ifirm('B1'), _ifirm('B2')
        _contract('10/25-YGT-EXP', ygt, b1, seq=10, year=2025)
        _contract('20/25-YGT-EXP', ygt, b2, seq=20, year=2025)
        # Two different buyers share one YGT-2025 sequence — next is 21, not 11.
        self.assertEqual(next_contract_seq(ygt.id, 2025), 21)


class NextContractNoTest(TestCase):
    def test_allocates_next(self) -> None:
        ygt = _efirm('YGT')
        _contract('5/26-YGT-EXP', ygt, _ifirm('B1'), seq=5, year=2026)
        seq, year, number = next_contract_no(ygt, datetime.date(2026, 1, 6))
        self.assertEqual((seq, year), (6, 2026))
        self.assertEqual(number, '6/26-YGT-EXP, 06.01.2026')


class UniqueConstraintTest(TestCase):
    def test_same_firm_year_seq_rejected(self) -> None:
        ygt = _efirm('YGT')
        b1, b2 = _ifirm('B1'), _ifirm('B2')
        _contract('5/25-YGT-EXP, 01.01.2025', ygt, b1, seq=5, year=2025)
        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                # Different string, same (firm, year, seq) → constraint fires.
                _contract('5/25-YGT-EXP, 02.02.2025', ygt, b2, seq=5, year=2025)

    def test_null_seq_not_constrained(self) -> None:
        ygt = _efirm('YGT')
        b1, b2 = _ifirm('B1'), _ifirm('B2')
        # Two non-standard contracts (NULL seq/year) must coexist.
        _contract('177-AM-P', ygt, b1)
        _contract('TAT-AM/01', ygt, b2)
        self.assertEqual(Contract.objects.filter(seq__isnull=True).count(), 2)


class SerializerAutoNumberTest(TestCase):
    def _create(self, data: dict) -> Contract:
        ser = ContractCreateSerializer(data=data, context={})
        ser.is_valid(raise_exception=True)
        return ser.save()

    def test_blank_number_is_autogenerated(self) -> None:
        ygt = _efirm('YGT')
        _contract('40/26-YGT-EXP', ygt, _ifirm('B0'), seq=40, year=2026)
        contract = self._create({
            'export_firm': ygt.id,
            'import_firm': _ifirm('B1').id,
            'start_date': '2026-01-06',
        })
        self.assertEqual(contract.seq, 41)
        self.assertEqual(contract.contract_year, 2026)
        self.assertEqual(contract.contract_number, '41/26-YGT-EXP, 06.01.2026')

    def test_supplied_standard_number_parses_seq_year(self) -> None:
        ygt = _efirm('YGT')
        contract = self._create({
            'export_firm': ygt.id,
            'import_firm': _ifirm('B1').id,
            'contract_number': '99/25-YGT-EXP, 22.09.2025',
            'start_date': '2025-09-22',
        })
        self.assertEqual(contract.contract_number, '99/25-YGT-EXP, 22.09.2025')
        self.assertEqual((contract.seq, contract.contract_year), (99, 2025))

    def test_supplied_non_standard_number_leaves_seq_null(self) -> None:
        ygt = _efirm('YGT')
        contract = self._create({
            'export_firm': ygt.id,
            'import_firm': _ifirm('B1').id,
            'contract_number': '177-AM-P',
            'start_date': '2025-09-22',
        })
        self.assertEqual(contract.contract_number, '177-AM-P')
        self.assertIsNone(contract.seq)
        self.assertIsNone(contract.contract_year)
